import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireOrganization} from '@/lib/server/auth';
import {invoiceFields} from '@/lib/invoices';
import {invoiceRows,addInvoicePayment,addInvoiceFollowup} from '@/lib/server/invoices';
export async function GET(){const a=await requireOrganization();if('error'in a)return a.error;try{const names=['invoices','invoice_payments','invoice_followups','invoice_history','clients','events','proposals','financial_documents','invoice_import_rows'];const r=await Promise.all(names.map(t=>invoiceRows(a.supabase,a.membership.organization_id,t)));return NextResponse.json({collectionSources:r[8],invoices:r[0].map(i=>({...i,original_document_id:r[7].find(d=>d.invoice_id===i.id)?.id})),payments:r[1],followups:r[2],history:r[3],clients:r[4].map(c=>({id:c.id,company_name:c.company_name})),events:r[5].map(e=>({id:e.id,event_name:e.event_name,event_date:e.event_date,venue:e.venue,client_id:e.client_id})),proposals:r[6].map(p=>({id:p.id,title:p.title,client_id:p.client_id})),canEdit:['admin','producer','sales'].includes(a.membership.role)})}catch{return NextResponse.json({error:'No se pudieron cargar las facturas.'},{status:500})}}
import {invoiceToday} from '@/lib/invoices';
const requestSchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('save'),id:z.string().uuid(),version:z.number().int().positive().optional(),fields:invoiceFields}),
 z.object({action:z.literal('payment'),id:z.string().uuid(),invoice_id:z.string().uuid(),payment_date:z.string().date(),amount_cents:z.number().int().positive().max(100000000000),currency:z.string().regex(/^[A-Z]{3}$/),method:z.string().max(200),reference:z.string().max(500),note:z.string().max(10000)}),
 z.object({action:z.literal('followup'),id:z.string().uuid(),invoice_id:z.string().uuid(),followup_date:z.string().date(),kind:z.enum(['email','whatsapp','call','reply','promise','reminder','other']),note:z.string().trim().min(1).max(10000),next_action:z.string().max(500),next_action_date:z.string().date().nullable()}),
 z.object({action:z.literal('mark_paid'),id:z.string().uuid()})]);
export async function POST(req:Request){const a=await requireOrganization();if('error'in a)return a.error;if(!['admin','producer','sales'].includes(a.membership.role))return NextResponse.json({error:'No puedes editar facturas.'},{status:403});const p=requestSchema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:p.error.issues[0].message},{status:400});const b=p.data,org=a.membership.organization_id;
 try{if(b.action==='save'){const r=b.version?await a.supabase.from('invoices').update(b.fields).eq('organization_id',org).eq('id',b.id).eq('version',b.version).select('id'):await a.supabase.from('invoices').insert({...b.fields,id:b.id,organization_id:org,created_by:a.userId}).select('id');if(r.error)throw r.error;if(!r.data?.length)return NextResponse.json({error:'La factura ha cambiado. Cierra y vuelve a abrir su ficha.'},{status:409});}else if(b.action==='mark_paid'){const [invRes,payRes]=await Promise.all([a.supabase.from('invoices').select('*').eq('organization_id',org).eq('id',b.id).single(),a.supabase.from('invoice_payments').select('amount_cents,currency').eq('organization_id',org).eq('invoice_id',b.id)]);if(invRes.error||!invRes.data)return NextResponse.json({error:'Factura no encontrada.'},{status:404});const inv=invRes.data,paid=(payRes.data||[]).reduce((s,p)=>s+p.amount_cents,0),pending=inv.total_cents-paid;if(pending>0){await addInvoicePayment(a.supabase,org,a.userId,{invoice_id:inv.id,payment_date:invoiceToday(),amount_cents:pending,currency:inv.currency,method:'Cobro directo',reference:'Marcado pagado',note:'Marcado rápidamente como pagado'});}await a.supabase.from('invoices').update({status:'paid'}).eq('organization_id',org).eq('id',b.id);}else{const {action,...fields}=b;if(action==='payment')await addInvoicePayment(a.supabase,org,a.userId,fields);else await addInvoiceFollowup(a.supabase,org,a.userId,fields)}return NextResponse.json({ok:true});}catch(e){const err=e as {code?:string;message?:string};return NextResponse.json({error:err.code==='23505'?'Este número o registro ya existe. Actualiza antes de repetir.':err.code==='P0001'?err.message:'No se pudo guardar. Revisa los datos y sus relaciones.'},{status:400})}}

