import {it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
const org='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',user='33333333-3333-4333-8333-333333333333';
it('keeps bank evidence immutable, supports split payments, prevents over-allocation and requires duplicate review',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role authenticated;create role anon;create schema auth;create function auth.uid() returns uuid language sql as 'select ''${user}''::uuid';
 create table organizations(id uuid primary key);create table users(id uuid primary key);create table clients(id uuid primary key);
 create table talent(id uuid primary key);create table events(id uuid primary key,organization_id uuid,event_name text,event_date date,status text,deleted_at timestamptz);
 create table event_talent(event_id uuid,talent_id uuid,organization_id uuid,agreed_cost_cents bigint,notes text,unique(event_id,talent_id));
 create table payments(id uuid primary key,organization_id uuid,talent_id uuid,event_id uuid,amount_cents bigint,status text,paid_on date,created_at timestamptz,kind text,direction text);
 create function has_org_role(o uuid,text[]) returns boolean language sql as 'select o=''${org}''::uuid';
 create function enforce_tenant_references() returns trigger language plpgsql as 'begin return new;end';
 insert into organizations values('${org}'),('${other}');insert into users values('${user}');`);
 await db.exec(readFileSync('supabase/migrations/202609140014_expenses.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/202609140019_bank_reconciliation.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/202609140020_bank_consistency.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/202609140021_bank_csv_import.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/202609140022_bank_artist_work.sql','utf8'));
 const cat=(await db.query<{id:string}>('select id from expense_categories where organization_id=$1 limit 1',[org])).rows[0].id;
 const supplier=(await db.query<{id:string}>("insert into suppliers(organization_id,name,normalized_name) values($1,'Provider','provider') returning id",[org])).rows[0].id;
 const expense=async(total:number)=> (await db.query<{id:string}>("insert into expenses(organization_id,supplier_id,supplier_name,category_id,expense_date,concept,total_cents,currency) values($1,$2,'Provider',$3,'2026-07-01','Work',$4,'EUR') returning id",[org,supplier,cat,total])).rows[0].id;
 let row=1;
 const bank=async(amount:number,issues:string[]=[])=>(await db.query<{id:string}>("insert into bank_movements(organization_id,source_key,fingerprint,occurrence,source_file,source_hash,source_sheet,source_row,payment_date,amount_cents,currency,original_reference,original_concept,source_data,supplier_id,status,issues) values($1,$2,$2,1,'source.xlsx','hash','Todos',$3,'2026-07-01',$4,'EUR','Reference','Original','{}',$5,'review',$6) returning id",[org,'row-'+row,row++,amount,supplier,issues])).rows[0].id;
 const pay=(movement:string,e:string,amount:number)=>db.query('select reconcile_bank_payment($1,$2,$3)',[movement,e,amount]);
 const e1=await expense(600),e2=await expense(400),b1=await bank(1000);
 await pay(b1,e1,600);await pay(b1,e2,400);
 expect((await db.query<{status:string}>('select status from bank_movements where id=$1',[b1])).rows[0].status).toBe('reconciled');
 await expect(pay(b1,await expense(100),100)).rejects.toThrow(/supera/);
 const b2=await bank(500);await expect(pay(b2,e1,100)).rejects.toThrow(/saldo/);
 expect((await db.query('select * from expense_payments where bank_movement_id=$1',[b2])).rows).toHaveLength(0);
 const e3=await expense(600);await pay(await bank(300),e3,300);await pay(await bank(300),e3,300);
 expect((await db.query<{paid:number}>('select sum(amount_cents)::int as paid from expense_payments where expense_id=$1',[e3])).rows[0].paid).toBe(600);
 const duplicate=await bank(200,['duplicate']),e4=await expense(200);
 await expect(pay(duplicate,e4,200)).rejects.toThrow(/duplicado/);
 await db.query("select review_bank_movement($1,1,$2,null,null,'other','Confirmed two different invoices')",[duplicate,supplier]);await pay(duplicate,e4,200);
 await expect(db.query('update bank_movements set amount_cents=1 where id=$1',[b1])).rejects.toThrow(/inmutable/);
 await expect(db.query("update bank_movements set status='reconciled' where id=$1",[b2])).rejects.toThrow(/asigna/);
 await expect(db.query('update expenses set supplier_id=null where id=$1',[e1])).rejects.toThrow(/relaciones/);
 await expect(db.query("select review_bank_movement($1,1,$2,null,null,'other','stale')",[duplicate,supplier])).rejects.toThrow(/ha cambiado/);
 await expect(db.query("insert into bank_movements select gen_random_uuid(),organization_id,source_key,fingerprint,occurrence,source_file,source_hash,source_sheet,source_row,payment_date,amount_cents,currency,original_reference,original_concept,source_data,supplier_id,talent_id,event_id,expected_cents,suggested_event_ids,status,issues,resolution_reason,resolution_note,version,created_by,created_at from bank_movements where id=$1",[b1])).rejects.toThrow(/unique/);
 const csvRows=[1,2].map(i=>({source_key:'csv-'+i,fingerprint:'identical-csv',occurrence:i,source_file:'source.csv',source_hash:'hash',source_row:i+1,payment_date:'2026-08-03',amount_cents:89515,original_reference:'2026-2149',original_concept:'Transferencia',source_data:{}}));
 const csv=async()=>db.query<{result:{imported:number;skipped:number}}>('select import_bank_csv($1,$2) as result',[org,JSON.stringify(csvRows)]);
 expect((await csv()).rows[0].result).toEqual({imported:2,skipped:0});expect((await csv()).rows[0].result).toEqual({imported:0,skipped:2});
 expect((await db.query("select * from bank_movements where fingerprint='identical-csv' and 'duplicate'=any(issues)")).rows).toHaveLength(2);
 const artist='44444444-4444-4444-8444-444444444444',event='55555555-5555-4555-8555-555555555555';
 await db.query('insert into talent values($1)',[artist]);await db.query("insert into events(id,organization_id,event_name,event_date,status) values($1,$2,'Work','2026-07-01','completed')",[event,org]);
 const workExpense=await expense(100),workBank=await bank(100);
 await db.query('update expenses set talent_id=$2,event_id=$3 where id=$1',[workExpense,artist,event]);
 await db.query("select review_bank_movement($1,1,$2,$3,$4,'other','Work confirmed')",[workBank,supplier,artist,event]);await pay(workBank,workExpense,100);
 expect((await db.query('select * from event_talent where event_id=$1 and talent_id=$2',[event,artist])).rows).toHaveLength(1);
 expect((await db.query('select * from expenses where event_id=$1 and talent_id=$2',[event,artist])).rows).toHaveLength(1);
 }finally{await db.close()}
},20000);
