import {describe,it,expect} from 'vitest';
import {contextRequestSchema,type ContextGraph,type ContextRequest,type ContextRow} from '../lib/chatgpt/contracts';
import {cleanContext} from '../lib/chatgpt/privacy';import {buildChatGPTContext} from '../lib/chatgpt/build-context';
import {getChatGPTContext} from '../lib/server/chatgpt/context-service';import type {ContextRepository} from '../lib/server/chatgpt/repository';
import {newProposal,newLine} from '../lib/proposals';
const input:ContextRequest={entityType:'client',entityId:'11111111-1111-4111-8111-111111111111',action:'reply-client',customQuestion:'',includePersonalData:false};
const graph=():ContextGraph=>({root:'client',rootId:input.entityId,capturedAt:'2026-09-13T12:00:00Z',clients:[{id:input.entityId,company_name:'Cliente real',email:'client@example.com',phone:'+34 642 345 678',notes:'Quiere una propuesta premium. Email: client@example.com\nDomicilio: Calle Mayor 10'}],leads:[],opportunities:[],events:[],proposals:[],shows:[],performers:[],assignments:[],payments:[],activities:[],tasks:[],historyEvents:[],historyProposals:[]});
describe('Context privacy and structure',()=>{
 it('omits empty values while retaining zero and false',()=>{expect(cleanContext({email:null,venue:undefined,phone:'',zero:0,paid:false,array:[],nested:{x:''}})).toEqual({zero:0,paid:false});});
 it('excludes personal data by default, including contacts repeated in free text',()=>{const g=graph();g.tasks.push({title:'Revisar',description:'Contacto alternativo: second@example.com, 612345678'});const p=buildChatGPTContext(g,input).prompt;expect(p).toContain('Cliente real');for(const value of ['client@example.com','second@example.com','642 345 678','612345678','Calle Mayor'])expect(p).not.toContain(value);expect(p).not.toContain('"Email":');expect(p).not.toContain('null');expect(p).not.toContain('undefined');});
 it('includes contact fields only when explicitly requested',()=>{const p=buildChatGPTContext(graph(),{...input,includePersonalData:true}).prompt;expect(p).toContain('client@example.com');expect(p).toContain('+34 642 345 678');});
 it('preserves budget/date, records known zero and never invents missing margin',()=>{const g=graph();g.events=[{id:'e',event_name:'Mi evento',event_date:'2026-10-01',income_cents:140000,expenses_cents:null,other_expenses_cents:null,client_paid:false}];const p=buildChatGPTContext(g,input).prompt;expect(p).toContain('Mi evento');expect(p).toContain('2026-10-01');expect(p).toContain('1400.00 EUR');expect(p).toContain('No pagado');expect(p).not.toContain('"Beneficio bruto"');g.events[0].income_cents=123456789;expect(buildChatGPTContext(g,input).prompt).toContain('1234567.89 EUR');});
 it('includes proposal sale/cost bases and explicitly protects client drafts',()=>{const g=graph(),q=newProposal();q.title='Oferta';q.options[0].lines=[{...newLine(),label:'Equipo',quantity:4,unit_price_cents:35000,internal_cost_cents:95000}];g.proposals=[{id:'p',title:q.title,version:2,document:q}];const p=buildChatGPTContext(g,{...input,action:'review-budget'}).prompt;expect(p).toContain('Oferta');expect(p).toContain('1400.00 EUR');expect(p).toContain('950.00 EUR');expect(p).toContain('450.00 EUR');expect(p).toContain('no reveles costes');expect(p).toContain('No hay versiones anteriores');});
 it('validates entity IDs and rejects caller-supplied organisation',()=>{expect(contextRequestSchema.safeParse(input).success).toBe(true);expect(contextRequestSchema.safeParse({...input,organization_id:'other'}).success).toBe(false);expect(contextRequestSchema.safeParse({...input,entityType:'users'}).success).toBe(false);});
});
describe('Real relation traversal',()=>{
 const records:Record<string,ContextRow[]>={clients:[{id:'c'}],leads:[{id:'l',client_id:'c'}],opportunities:[{id:'o',client_id:'c',lead_id:'l',event_id:'e'}],proposals:[{id:'p',opportunity_id:'o',event_id:'e',client_id:'c',document:{options:[{lines:[{show_ids:['s']}]}]}}],events:[{id:'e',client_id:'c'},{id:'old',client_id:'c'}],event_shows:[{event_id:'e',show_id:'s'}],shows:[{id:'s'}],event_talent:[{event_id:'e',talent_id:'t'}],talent:[{id:'t'}]};
 const repo:ContextRepository={async find(table,key,ids){return (records[table]||[]).filter(r=>ids.includes(r[key] as string));}};
 it('joins lead, opportunity, client, event, show and performer once',async()=>{const g=await getChatGPTContext(repo,{...input,entityType:'proposal',entityId:'p'});expect(g.clients.map(x=>x.id)).toEqual(['c']);expect(g.leads.map(x=>x.id)).toEqual(['l']);expect(g.events.map(x=>x.id)).toEqual(['e']);expect(g.shows.map(x=>x.id)).toEqual(['s']);expect(g.performers.map(x=>x.id)).toEqual(['t']);expect(g.historyEvents.map(x=>x.id)).toEqual(['old']);expect(g.historyProposals).toEqual([]);});
 it('fails closed if the root is missing or inaccessible',async()=>{await expect(getChatGPTContext(repo,{...input,entityId:'other'})).rejects.toThrow('no disponible');});
});

describe('Explicit copy and open',()=>{
 it('copies exactly the edited prompt before opening the external page',async()=>{const {copyChatGPTContext}=await import('../lib/chatgpt/clipboard');const events:string[]=[];await copyChatGPTContext('Texto editado',async text=>{events.push(text);},()=>{events.push('open');});expect(events).toEqual(['Texto editado','open']);});
 it('does not open anything if the clipboard rejects the operation',async()=>{const {copyChatGPTContext}=await import('../lib/chatgpt/clipboard');let opened=false;await expect(copyChatGPTContext('Texto',async()=>{throw Error('blocked');},()=>{opened=true;})).rejects.toThrow('blocked');expect(opened).toBe(false);});
});
