import {describe,it,expect} from 'vitest';
import {newProposal,newLine,proposalSchema,optionMoney,proposalText} from '../lib/proposals';
import {proposalPdf} from '../lib/proposal-pdf';
import {PDFDocument} from 'pdf-lib';
import {mkdirSync,writeFileSync} from 'node:fs';
const fixture=()=>{const p=newProposal();p.title='Espectáculo de prueba · control de formato';p.client_name='Cliente de prueba';p.event_date='2026-10-01';p.venue='Venue de prueba';p.city='Ibiza';p.internal_notes='SECRETO_INTERNO_7654';p.brief='Una propuesta visual para dar comienzo a la fiesta. Este documento es exclusivamente una prueba de formato.';p.options[0].lines=[{...newLine(),label:'Personajes visuales',quantity:4,unit_price_cents:35000,internal_cost_cents:95000,cost_basis:'total',sets:'2 pases incluidos',duration:'15 minutos por pase',wardrobe:'Cambio de personajes entre pases'}];return p;};
describe('Performance Lab proposals',()=>{
 it('keeps a team cost separate from performer sale and does not charge included sets',()=>{const p=fixture(),m=optionMoney(p.options[0],null);expect(m.net).toBe(140000);expect(m.cost).toBe(95000);expect(m.profit).toBe(45000);expect(m.total).toBeNull();expect(m.margin).toBeCloseTo(32.142857);});
 it('does not treat missing prices or costs as zero totals',()=>{const p=fixture();p.options[0].lines[0].unit_price_cents=null;expect(optionMoney(p.options[0],21)).toMatchObject({complete:false,total:null,profit:null,margin:null});p.options[0].lines[0].unit_price_cents=35000;p.options[0].lines[0].internal_cost_cents=null;expect(optionMoney(p.options[0],21)).toMatchObject({costsComplete:false,profit:null,margin:null,total:169400});});
 it('calculates days and discounts before VAT and keeps alternatives separate',()=>{const p=fixture();p.options[0].lines[0].unit='performer_day';p.options[0].lines[0].units=2;p.options[0].discount_cents=10000;expect(optionMoney(p.options[0],21)).toMatchObject({net:270000,total:326700});const copy=structuredClone(p.options[0]);copy.id=crypto.randomUUID();copy.title='Alternative';copy.lines[0].id=crypto.randomUUID();p.options.push(copy);expect(proposalText(p)).toContain('alternativas independientes');});
 it('rejects duplicate line IDs, invalid acceptance and excessive discount',()=>{const p=fixture();p.status='accepted';expect(proposalSchema.safeParse(p).success).toBe(false);p.selected_option_id=p.options[0].id;expect(proposalSchema.safeParse(p).success).toBe(true);p.options[0].lines.push(p.options[0].lines[0]);expect(proposalSchema.safeParse(p).success).toBe(false);});
 it('never includes internal fields in either client language',()=>{for(const language of ['es','en'] as const){const p=fixture();p.language=language;const text=proposalText(p);expect(text).not.toContain('SECRETO_INTERNO');expect(text).not.toContain('950');expect(text).not.toContain('32.14');expect(text).toContain('1');}});
 it('renders a multi-page PDF without leaking internal fields',async()=>{const p=fixture();p.conditions='Viaje y alojamiento pendientes de confirmar. '.repeat(100);const bytes=await proposalPdf(p,'QA-NO-ENVIAR');expect((await PDFDocument.load(bytes)).getPageCount()).toBeGreaterThan(1);if(process.env.PLAB_PDF_QA){mkdirSync('tmp/pdfs',{recursive:true});writeFileSync('tmp/pdfs/propuesta-qa.pdf',bytes);}});
});
