import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireOrganization} from '@/lib/server/auth';
import {invoiceRows} from '@/lib/server/invoices';
const amount=z.number().int().min(0).max(100000000000).nullable(),id=z.string().uuid().nullable();
const fields=z.object({talent_id:id,supplier_name:z.string().max(500),supplier_id:id.optional(),invoice_date:z.string().date().nullable().optional(),work_date:z.string().date().nullable().optional(),retention_cents:amount.optional(),event_id:id,category_id:z.string().uuid(),number:z.string().max(200),expense_date:z.string().date(),due_date:z.string().date().nullable(),concept:z.string().trim().min(1).max(10000),base_cents:amount,tax_cents:amount,total_cents:amount,estimated_cents:amount,currency:z.string().regex(/^[A-Z]{3}$/),status:z.enum(['missing','received','pending','cancelled']),document_url:z.union([z.literal(''),z.string().url().refine(v=>/^https?:\/\//.test(v))]),notes:z.string().max(10000)}).strict().refine(f=>f.talent_id||f.supplier_name.trim(),'Selecciona artista/proveedor o escribe su nombre');
const schema=z.discriminatedUnion('action',[
 z.object({action:z.literal('save'),id:z.string().uuid(),version:z.number().int().positive().optional(),fields}),
 z.object({action:z.literal('payment'),id:z.string().uuid(),expense_id:z.string().uuid(),payment_date:z.string().date(),amount_cents:z.number().int().positive().max(100000000000),currency:z.string().regex(/^[A-Z]{3}$/),method:z.string().max(200),reference:z.string().max(500),note:z.string().max(10000)}),
 z.object({action:z.literal('followup'),id:z.string().uuid(),expense_id:z.string().uuid(),followup_date:z.string().date(),kind:z.enum(['email','whatsapp','call','reply','promise','reminder','other']),note:z.string().trim().min(1).max(10000),next_action:z.string().max(500),next_action_date:z.string().date().nullable()}),
 z.object({action:z.literal('category'),name:z.string().trim().min(1).max(100),category_group:z.enum(['Artistas','Producción','Viajes','Empresa'])})]);
export async function GET(){const a=await requireOrganization();if('error'in a)return a.error;try{const tables=['expenses','expense_payments','expense_followups','expense_history','expense_categories','talent','events','payments','suppliers'];const r=await Promise.all(tables.map(t=>invoiceRows(a.supabase,a.membership.organization_id,t)));const assignments=await a.supabase.from('event_talent').select('event_id,talent_id,agreed_cost_cents').eq('organization_id',a.membership.organization_id).range(0,999);if(assignments.error)throw assignments.error;const legacy=r[0].flatMap(e=>{const p=r[7].find(p=>p.id===e.legacy_payment_id&&p.status==='paid');return p?[{id:p.id,expense_id:e.id,payment_date:p.paid_on||String(p.created_at).slice(0,10),amount_cents:p.amount_cents,currency:'EUR',method:'',reference:'',note:'Pago histórico registrado en Pagos',created_at:p.created_at}]:[]});return NextResponse.json({suppliers:r[8].filter(s=>!s.merged_into),expenses:r[0],payments:[...r[1],...legacy],followups:r[2],history:r[3],categories:r[4],talent:r[5].filter(t=>!t.deleted_at&&!t.merged_into).map(t=>({id:t.id,real_name:t.real_name})),events:r[6].map(e=>({id:e.id,event_name:e.event_name,event_date:e.event_date,venue:e.venue,income_cents:e.income_cents,expenses_cents:e.expenses_cents,other_expenses_cents:e.other_expenses_cents})),assignments:assignments.data,canEdit:['admin','producer'].includes(a.membership.role)})}catch{return NextResponse.json({error:'No se pudieron cargar los gastos.'},{status:500})}}
export async function POST(req:Request){const a=await requireOrganization();if('error'in a)return a.error;if(!['admin','producer'].includes(a.membership.role))return NextResponse.json({error:'No puedes editar gastos.'},{status:403});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:p.error.issues[0].message},{status:400});const b=p.data,org=a.membership.organization_id;try{if(b.action==='save'){const q=b.version?await a.supabase.from('expenses').update(b.fields).eq('organization_id',org).eq('id',b.id).eq('version',b.version).select('id'):await a.supabase.from('expenses').insert({...b.fields,id:b.id,organization_id:org,created_by:a.userId}).select('id');if(q.error)throw q.error;if(!q.data?.length)return NextResponse.json({error:'El gasto ha cambiado. Cierra y vuelve a abrirlo.'},{status:409})}else{const {action,...payload}=b;const table=action==='payment'?'expense_payments':action==='followup'?'expense_followups':'expense_categories';const r=await a.supabase.from(table).insert({...payload,organization_id:org,...(action==='category'?{}:{created_by:a.userId})});if(r.error)throw r.error}return NextResponse.json({ok:true})}catch(e){const err=e as {code?:string;message?:string};return NextResponse.json({error:err.code==='23505'?'Ya existe este registro o un gasto para ese artista y evento. Abre la ficha existente.':err.code==='P0001'?err.message:'No se pudo guardar el gasto.'},{status:400})}}
