import {NextResponse} from 'next/server';
import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {requireOrganization} from '@/lib/server/auth';
import {invoiceRows} from '@/lib/server/invoices';
import {documentMime,maxDocumentBytes} from '@/lib/financial-documents';
export const runtime='nodejs';
export async function GET(request:Request){const a=await requireOrganization();if('error'in a)return a.error;
 try{const id=new URL(request.url).searchParams.get('id');if(id){const {data:d,error}=await a.supabase.from('financial_documents').select('*').eq('id',id).eq('organization_id',a.membership.organization_id).single();if(error||!d)return NextResponse.json({error:'Documento no disponible.'},{status:404});const link=await a.supabase.storage.from('financial-originals').createSignedUrl(d.storage_path,60,{download:d.filename});if(link.error)throw link.error;return NextResponse.redirect(link.data.signedUrl)}
 const documents=await invoiceRows(a.supabase,a.membership.organization_id,'financial_documents');return NextResponse.json({documents:documents.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))})
 }catch{return NextResponse.json({error:'No se pudieron cargar los documentos.'},{status:500})}}
export async function POST(request:Request){const a=await requireOrganization();if('error'in a)return a.error;if(!['admin','producer','sales'].includes(a.membership.role))return NextResponse.json({error:'No tienes permiso para subir documentos.'},{status:403});
 try{if(Number(request.headers.get('content-length')||0)>maxDocumentBytes+1048576)return NextResponse.json({error:'Máximo 20 MB por archivo.'},{status:413});const form=await request.formData(),file=form.get('file');if(!(file instanceof File)||!file.size||file.size>maxDocumentBytes)return NextResponse.json({error:'Selecciona un archivo de hasta 20 MB.'},{status:400});const bytes=Buffer.from(await file.arrayBuffer()),mime=documentMime(bytes);if(!mime)return NextResponse.json({error:'Formato no admitido. Usa PDF, JPG, PNG o HEIC.'},{status:400});const sha256=createHash('sha256').update(bytes).digest('hex'),org=a.membership.organization_id;
 const existing=await a.supabase.from('financial_documents').select('id,filename').eq('organization_id',org).eq('sha256',sha256).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return NextResponse.json({duplicate:true,document:existing.data});
 const id=randomUUID(),path=org+'/'+id+'/original';const upload=await a.supabase.storage.from('financial-originals').upload(path,bytes,{contentType:mime,upsert:false});if(upload.error)throw upload.error;
 const saved=await a.supabase.from('financial_documents').insert({id,organization_id:org,filename:file.name.slice(0,250),storage_path:path,mime_type:mime,size_bytes:file.size,sha256,created_by:a.userId}).select('id,filename').single();
 if(saved.error){await a.supabase.storage.from('financial-originals').remove([path]);if(saved.error.code==='23505'){const duplicate=await a.supabase.from('financial_documents').select('id,filename').eq('organization_id',org).eq('sha256',sha256).single();if(duplicate.data)return NextResponse.json({duplicate:true,document:duplicate.data})}throw saved.error}return NextResponse.json({document:saved.data});
 }catch{return NextResponse.json({error:'No se pudo guardar el archivo. Puedes volver a intentarlo.'},{status:500})}}
const patch=z.object({id:z.string().uuid(),invoice_id:z.string().uuid().nullable(),expense_id:z.string().uuid().nullable(),notes:z.string().max(10000)}).refine(v=>!v.invoice_id||!v.expense_id);
export async function PATCH(request:Request){const a=await requireOrganization();if('error'in a)return a.error;const p=patch.safeParse(await request.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'Revisa los campos.'},{status:400});const {id,...fields}=p.data;const r=await a.supabase.from('financial_documents').update({...fields,status:fields.invoice_id||fields.expense_id?'linked':'pending'}).eq('id',id).eq('organization_id',a.membership.organization_id).select('id');if(r.error||!r.data?.length)return NextResponse.json({error:'No se pudo guardar la ficha.'},{status:400});return NextResponse.json({ok:true})}
