export const importedExpenses = [
  {
    "id": "G001",
    "date": "03/04/2026",
    "eventId": "EV001",
    "eventName": "LA MOVIDA",
    "concept": "Artistas show",
    "artist": "Charlie",
    "amount": 140.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G002",
    "date": "03/04/2026",
    "eventId": "EV001",
    "eventName": "LA MOVIDA",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 140.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G003",
    "date": "03/04/2026",
    "eventId": "EV001",
    "eventName": "LA MOVIDA",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 140.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G004",
    "date": "03/04/2026",
    "eventId": "EV001",
    "eventName": "LA MOVIDA",
    "concept": "Artistas show",
    "artist": "Omar Fraile Wiki",
    "amount": 140.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G005",
    "date": "03/04/2026",
    "eventId": "EV002",
    "eventName": "LORE",
    "concept": "Artistas show",
    "artist": "Duarte",
    "amount": 140.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G006",
    "date": "03/04/2026",
    "eventId": "EV002",
    "eventName": "LORE",
    "concept": "Artistas show",
    "artist": "Kiko",
    "amount": 140.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G007",
    "date": "11/04/2026",
    "eventId": "EV003",
    "eventName": "ARTE VOLANTE",
    "concept": "Artistas show",
    "artist": "tabita",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G008",
    "date": "11/04/2026",
    "eventId": "EV003",
    "eventName": "ARTE VOLANTE",
    "concept": "Artistas show",
    "artist": "afrika",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G009",
    "date": "11/04/2026",
    "eventId": "EV003",
    "eventName": "ARTE VOLANTE",
    "concept": "Artistas show",
    "artist": "julieta",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G010",
    "date": "11/04/2026",
    "eventId": "EV003",
    "eventName": "ARTE VOLANTE",
    "concept": "Artistas show",
    "artist": "mariela",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G011",
    "date": "11/04/2026",
    "eventId": "EV004",
    "eventName": "CUMPLEAÑOS VLC",
    "concept": "Artistas show",
    "artist": "CRISTIAN SOLAZ GILABERT",
    "amount": 140.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G012",
    "date": "11/04/2026",
    "eventId": "EV004",
    "eventName": "CUMPLEAÑOS VLC",
    "concept": "Artistas show",
    "artist": "Charlie",
    "amount": 140.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G013",
    "date": "18/04/2026",
    "eventId": "EV005",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Laura",
    "amount": 120.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G014",
    "date": "18/04/2027",
    "eventId": "EV005",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "krys",
    "amount": 120.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G015",
    "date": "18/04/2028",
    "eventId": "EV005",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "cinthya",
    "amount": 120.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G016",
    "date": "18/04/2029",
    "eventId": "EV005",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "feli",
    "amount": 120.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G017",
    "date": "2026-04-25",
    "eventId": "EV006",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 140.0,
    "paymentStatus": "Pendiente",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G018",
    "date": "2026-04-25",
    "eventId": "EV006",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Vo",
    "amount": 120.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G018",
    "date": "2026-04-25",
    "eventId": "EV006",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Anthony",
    "amount": 500.0,
    "paymentStatus": "Pagado",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G019",
    "date": "2026-05-02",
    "eventId": "EV009",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G020",
    "date": "2026-05-14",
    "eventId": "EV015",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": "Efectivo",
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G021",
    "date": "2026-05-14",
    "eventId": "EV015",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G022",
    "date": "2026-05-14",
    "eventId": "EV015",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Krys",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G023",
    "date": "2026-05-15",
    "eventId": "EV016",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G024",
    "date": "2026-05-15",
    "eventId": "EV016",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G025",
    "date": "2026-05-15",
    "eventId": "EV016",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Charly",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G026",
    "date": "2026-05-15",
    "eventId": "EV016",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Omar",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G027",
    "date": "2026-05-15",
    "eventId": "EV016",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Cristian",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G028",
    "date": "2026-05-16",
    "eventId": "EV019",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Cristian",
    "amount": 200.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G029",
    "date": "2026-05-16",
    "eventId": "EV019",
    "eventName": "PRIVATE EVENT",
    "concept": "Artistas show",
    "artist": "Luella",
    "amount": 200.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G030",
    "date": "2026-05-20",
    "eventId": "EV020",
    "eventName": "ANIMACION POMPOM",
    "concept": "Artistas show",
    "artist": "Luella",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G031",
    "date": "2026-05-20",
    "eventId": "EV020",
    "eventName": "ANIMACION POMPOM",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G032",
    "date": "2026-05-20",
    "eventId": "EV020",
    "eventName": "ANIMACION POMPOM",
    "concept": "Artistas show",
    "artist": "Foves",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G033",
    "date": "2026-05-21",
    "eventId": "EV022",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G034",
    "date": "2026-05-21",
    "eventId": "EV022",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G035",
    "date": "2026-05-21",
    "eventId": "EV022",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Krys (otra persona)",
    "amount": 100.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G036",
    "date": "2026-05-22",
    "eventId": "EV023",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G037",
    "date": "2026-05-22",
    "eventId": "EV023",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G038",
    "date": "2026-05-22",
    "eventId": "EV023",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Charly",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G039",
    "date": "2026-05-22",
    "eventId": "EV023",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Omar",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G040",
    "date": "2026-05-22",
    "eventId": "EV023",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Cristian",
    "amount": 120.0,
    "paymentStatus": "Pendiente",
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G041",
    "date": "2026-05-23",
    "eventId": "EV024",
    "eventName": "ANIMACION VARIAS",
    "concept": "Artistas show",
    "artist": "Africa",
    "amount": 240.0,
    "paymentStatus": "Pendiente",
    "method": "Transferencia",
    "paidAt": null,
    "invoiceAmount": 290.4,
    "notes": "FACTURA FEDRIANI Nº 2026-1213 - ES98 0128 5605 5001 0000 3293"
  },
  {
    "id": "G042",
    "date": "2026-05-23",
    "eventId": "EV024",
    "eventName": "ANIMACION VARIAS",
    "concept": "Artistas show",
    "artist": "Luella",
    "amount": null,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G043",
    "date": "2026-05-25",
    "eventId": "EV027",
    "eventName": "MIRROR BALL HEAD",
    "concept": "Artistas show",
    "artist": "Luella",
    "amount": 290.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G044",
    "date": "2026-05-28",
    "eventId": "EV028",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 100.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G045",
    "date": "2026-05-28",
    "eventId": "EV028",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 100.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G046",
    "date": "2026-05-28",
    "eventId": "EV028",
    "eventName": "PROMO REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Africa",
    "amount": 100.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G047",
    "date": "2026-05-29",
    "eventId": "EV029",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Raul Fernandez de Cordoba Diaz",
    "amount": 120.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G048",
    "date": "2026-05-29",
    "eventId": "EV029",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Said",
    "amount": 120.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G049",
    "date": "2026-05-29",
    "eventId": "EV029",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Charly",
    "amount": 120.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G050",
    "date": "2026-05-29",
    "eventId": "EV029",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Omar",
    "amount": 120.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G051",
    "date": "2026-05-29",
    "eventId": "EV029",
    "eventName": "REMEMBERLAND",
    "concept": "Artistas show",
    "artist": "Cristian",
    "amount": 120.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G052",
    "date": "2026-05-25",
    "eventId": "EV030",
    "eventName": "PRIVATE EVENT",
    "concept": null,
    "artist": "Luella",
    "amount": 140.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  },
  {
    "id": "G053",
    "date": "2026-05-25",
    "eventId": "EV030",
    "eventName": "PRIVATE EVENT",
    "concept": null,
    "artist": "Eny",
    "amount": 140.0,
    "paymentStatus": null,
    "method": null,
    "paidAt": null,
    "invoiceAmount": null,
    "notes": null
  }
] as const;

