'use client';
import {DataReview} from './data-review';
import {ArtistBankPayments,SupplierProfile} from './bank-workspace';
import {payeeSummary} from '@/lib/payee-summary';
import type {BankData} from '@/lib/bank';
import {invoiceMoney} from '@/lib/invoices';
import {responseJson} from '@/lib/response-json';
import {useEffect,useState} from 'react';
type Artist={id:string;real_name:string;city?:string;skills?:string[];aliases?:string[];email?:string|null;phone?:string|null;tax_id?:string;iban?:string;billing_supplier_id?:string|null;billing_confidence?:string;deleted_at?:string|null};
type Event={id:string;event_name:string;event_date:string|null;client_id:string|null;venue:string|null};
type Assignment={event_id:string;talent_id:string;agreed_cost_cents:number};
type Payment={id:string;event_id:string;talent_id:string;amount_cents:number;status:string};
type Data={talent:Artist[];events:Event[];assignments:Assignment[];clients:{id:string;company_name:string}[];canEdit:boolean};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const date=(s:string|null)=>s?new Date(s).toLocaleDateString('es-ES',{timeZone:'Europe/Madrid'}):'Sin fecha';
function PayRow({event,amount,paid,canEdit,save}:{event:Event;amount:number|null;paid:boolean;canEdit:boolean;save:(amount:number,paid:boolean)=>Promise<void>}){
 const [value,setValue]=useState(amount===null?'':String(amount/100)),[checked,setChecked]=useState(paid);
 return <tr><td>{date(event.event_date)}</td><td>{event.event_name}<small>{event.venue}</small></td><td><input aria-label={'Sueldo de '+event.event_name} placeholder="Pendiente de indicar" type="number" min="0" max="1000000" step="0.01" value={value} disabled={!canEdit} onChange={e=>setValue(e.target.value)}/></td><td><select aria-label={'Pago de '+event.event_name} style={{color:checked?'#087e45':'#bf2635'}} value={checked?'paid':'pending'} disabled={!canEdit} onChange={e=>setChecked(e.target.value==='paid')}><option value="pending">No pagado</option><option value="paid">Pagado</option></select></td><td><button className="secondary-button" disabled={!canEdit||value===''||!Number.isFinite(Number(value))||Number(value)<0||Number(value)>1000000} onClick={()=>void save(Math.round(Number(value)*100),checked)}>Guardar</button></td></tr>;
}
export function ArtistProfiles({query,onBack}:{query:string;onBack:()=>void}){
 const [bank,setBank]=useState<BankData>(),[tab,setTab]=useState<'artist'|'supplier'>('artist'),[supplier,setSupplier]=useState<string|null>(null),[search,setSearch]=useState(''),[balanceFilter,setBalanceFilter]=useState('all');
 const [expenses,setExpenses]=useState<{id:string;talent_id:string;event_id:string;currency:string}[]>([]);
 const [data,setData]=useState<Data|null>(null),[payments,setPayments]=useState<Payment[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all');
 async function load(){try{const responses=await Promise.all(['/api/event-board','/api/artist-pay','/api/bank'].map(url=>fetch(url,{cache:'no-store'})));const [d,p,b]=await Promise.all(responses.map(responseJson));const failure=responses.findIndex(r=>!r.ok);if(failure>=0)throw Error([d,p,b][failure].error||'No se pudieron cargar los pagos');setData(d);setPayments(p.payments);setExpenses(p.expenses||[]);setBank(b);setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('focus',refresh);const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
 useEffect(()=>{const u=new URL(window.location.href),id=u.searchParams.get('talent');if(id&&data?.talent.some(a=>a.id===id)){setSelected(id);u.searchParams.delete('talent');window.history.replaceState(null,'',u)}},[data]);
 const artist=data?.talent.find(a=>a.id===selected);
 const works=(data?.assignments||[]).filter(a=>a.talent_id===selected).flatMap(a=>{const event=data?.events.find(e=>e.id===a.event_id);if(!event)return [];const ps=payments.filter(p=>p.event_id===a.event_id&&p.talent_id===selected);const amount=ps.length?ps.reduce((s,p)=>s+Number(p.amount_cents),0):Number(a.agreed_cost_cents)>0?Number(a.agreed_cost_cents):null;const paid=ps.filter(p=>p.status==='paid').reduce((s,p)=>s+Number(p.amount_cents),0);return [{event,amount,paid,settled:ps.length>0&&ps.every(p=>p.status==='paid')}];}).sort((a,b)=>(b.event.event_date||'').localeCompare(a.event.event_date||''));
 async function save(event_id:string,amount:number,paid:boolean){if(busy)return;setBusy(true);try{const r=await fetch('/api/artist-pay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id,talent_id:selected,amount,paid})});const p=await responseJson(r);if(!r.ok)throw Error(p.error);await load();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 const unfinished=works.filter(w=>!expenses.some(e=>e.talent_id===selected&&e.event_id===w.event.id));
 const searchText=normalize([query,search].filter(Boolean).join(' ')),tokens=searchText.split(/\s+/).filter(Boolean);
 const roster=data&&bank?(tab==='artist'?data.talent.map(a=>({id:a.id,name:a.real_name,description:[a.city,...(a.aliases||[]),...(a.skills||[])].filter(Boolean).join(' · '),deleted:Boolean(a.deleted_at)})):bank.suppliers.map(s=>({id:s.id,name:s.name,description:s.aliases.join(' · '),deleted:false}))).map(person=>({person,summary:payeeSummary(bank,tab,person.id),jobs:tab==='artist'?[...new Set(data.assignments.filter(a=>a.talent_id===person.id&&data.events.some(e=>e.id===a.event_id)).map(a=>a.event_id))].length:[...new Set(bank.expenses.filter(e=>e.supplier_id===person.id&&e.status!=='cancelled'&&e.event_id).map(e=>e.event_id))].length})).filter(r=>(tab==='supplier'||r.jobs||r.summary.expenses.length||r.summary.movements.length)&&tokens.every(t=>normalize(r.person.name+' '+r.person.description).includes(t))&&(balanceFilter==='all'||(balanceFilter==='pending'?r.summary.totals.some(t=>t.pending>0):balanceFilter==='unknown'?r.summary.unknown>0:r.summary.review>0))).sort((a,b)=>a.person.name.localeCompare(b.person.name,'es')):[];
 return <section className="data-module bank-workspace">
 <div className="module-head"><div><p className="eyebrow">TRABAJOS Y PAGOS</p><h1>{artist?.real_name||'Pagos a artistas y proveedores'}</h1><p>Consulta cada trabajo, completa sus importes y revisa lo pagado y lo pendiente.</p></div><button className="primary-button" onClick={()=>selected?setSelected(null):onBack()}>{selected?'Volver a pagos':'Volver a Mi día'}</button></div>
 <DataReview reloadParent={()=>void load()}/>{error&&<p role="alert">{error} <button onClick={()=>void load()}>Reintentar</button></p>}{!data&&!error&&<p>Cargando pagos…</p>}
 {data&&bank&&!selected&&<>
 <div className="crm-toolbar"><button className={tab==='artist'?'primary-button':'secondary-button'} aria-pressed={tab==='artist'} onClick={()=>setTab('artist')}>Artistas y bailarines</button><button className={tab==='supplier'?'primary-button':'secondary-button'} aria-pressed={tab==='supplier'} onClick={()=>setTab('supplier')}>Proveedores</button><input type="search" aria-label="Buscar en pagos" placeholder="Buscar por nombre, ciudad o habilidad…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar fichas de pagos" value={balanceFilter} onChange={e=>setBalanceFilter(e.target.value)}><option value="all">Todas las fichas</option><option value="pending">Con saldo pendiente</option><option value="unknown">Con importes por completar</option><option value="review">Con banco por revisar</option></select>{tab==='supplier'&&bank.canEdit&&<button className="secondary-button" onClick={()=>setSupplier('new')}>+ Añadir proveedor</button>}</div>
 <p>{roster.length} fichas. Los artistas aparecen cuando tienen trabajos o pagos vinculados. Los importes se calculan por moneda y no se suman entre artistas y proveedores.</p>
 <div className="data-table-wrap"><table className="data-table"><thead><tr>{['Nombre','Eventos vinculados','Gastos registrados','Pagos asignados','Saldo sin pago asignado','Por completar / revisar','Ficha'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{roster.map(({person,summary,jobs})=><tr key={person.id}><td><b>{person.name}</b><small>{person.description}{person.deleted?' · Archivado':''}</small></td><td>{jobs}</td>{(['total','paid','pending'] as const).map(key=><td key={key}>{summary.totals.length?summary.totals.map(t=><small key={t.currency}>{invoiceMoney(t[key],t.currency)}</small>):'Sin importe registrado'}</td>)}<td>{summary.unknown>0&&<small>{summary.unknown} importes por indicar</small>}{summary.review>0&&<small className="bank-warning">{summary.review} pagos bancarios por revisar</small>}{summary.totals.filter(t=>t.unallocated>0).map(t=><small key={t.currency}>{invoiceMoney(t.unallocated,t.currency)} en banco por asignar</small>)}{!summary.unknown&&!summary.review&&!summary.totals.some(t=>t.unallocated>0)&&'—'}</td><td><button className="secondary-button" onClick={()=>{if(tab==='artist'){setSelected(person.id);setFilter('all')}else setSupplier(person.id)}}>Abrir ficha</button></td></tr>)}</tbody></table>{!roster.length&&<p>No hay fichas con estos filtros.</p>}</div>
 <p>El banco puede contener pagos ya realizados que todavía faltan asignar a un gasto. El pago al proveedor no representa necesariamente el sueldo neto del artista.</p><a href="/?finance=bank#facturas">Abrir conciliación bancaria</a>
 </>}
 {artist&&<><section className="inv-related"><h2>Datos del artista</h2><p>Alias: {(artist.aliases||[]).join(", ")||"Sin alias"}</p><p>{artist.email||"Sin email"} · {artist.phone||"Sin teléfono"} · {artist.city||"Sin ciudad"}</p><p>Documento fiscal: {artist.tax_id||"Por confirmar"} · IBAN: {artist.iban||"Sin indicar"}</p><p>Empresa de facturación: {bank?.suppliers.find(s=>s.id===artist.billing_supplier_id)?.name||"Sin identificar"} {artist.billing_supplier_id&&artist.billing_confidence!=="confirmed"?"(por confirmar)":""}</p><p>{works.length} trabajos asignados; los fees, facturas y pagos se muestran a continuación.</p><a href={`/?artist=${artist.id}#talento`}>Editar su ficha de artista</a></section><ArtistBankPayments talentId={artist.id} sharedData={bank}/><h2>Asignaciones por completar</h2><p>Estos {unfinished.length} trabajos todavía no tienen una ficha de gasto vinculada. Al registrar su importe aquí, se conservará la relación con el evento. Sus importes acordados se muestran aquí y pasarán al registro de gastos al completar el evento.</p><select aria-label="Filtrar pagos" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos los trabajos por completar</option><option value="paid">Pagados</option><option value="pending">Pendientes</option><option value="unknown">Sin importe</option></select><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Evento</th><th>Importe acordado (€)</th><th>Pago al artista</th><th>Guardar cambios</th></tr></thead><tbody>{unfinished.filter(w=>filter==='all'||(filter==='unknown'?w.amount===null:filter==='paid'?w.settled:!w.settled)).map(w=><PayRow key={w.event.id+':'+w.amount+':'+w.paid} event={w.event} amount={w.amount} paid={w.settled} canEdit={Boolean(data?.canEdit)&&!busy} save={(amount,paid)=>save(w.event.id,amount,paid)}/>)}</tbody></table></div>{!unfinished.length&&<p>Todos sus trabajos asignados tienen ya una ficha de gasto, o todavía no hay eventos asignados.</p>}<p aria-live="polite">{busy?'Guardando…':'El cobro al cliente se controla por separado.'}</p></>}
 {supplier&&bank&&<SupplierProfile key={supplier} supplier={bank.suppliers.find(s=>s.id===supplier)} data={bank} close={()=>setSupplier(null)} reload={load} openBank={id=>{window.location.href=`/?finance=bank&movement=${id}#facturas`}}/>}
 </section>;
}
