'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Plus, Search, ChevronDown, ChevronRight, GripVertical, X, RefreshCw, ArrowUp, ArrowDown, Columns3, Archive, Users } from 'lucide-react';
import './client-board.css';

type Client={id:string;company_name:string;client_type:string;group_id:string;position:number;contact_name:string|null;phone:string|null;email:string|null;city:string|null;company:string|null;fiscal_data:string|null;notes:string|null;deleted_at:string|null;monday_source:Record<string,unknown>|null};
type Group={id:string;name:string;color:string;position:number};
type Event={id:string;event_name:string;event_date:string|null;client_id:string|null;status:string;venue:string|null};
type Data={clients:Client[];groups:Group[];events:Event[];canEdit:boolean;canLinkEvents:boolean};
const columns=[['contact_name','Persona de contacto'],['phone','Teléfono'],['client_type','Tipo de cliente'],['email','Email'],['city','Ciudad'],['company','Empresa'],['fiscal_data','Datos fiscales']] as const;
type Field=typeof columns[number][0];
const empty:Data={clients:[],groups:[],events:[],canEdit:false,canLinkEvents:false};

function Cell({value,label,disabled,onSave}:{value:string|null;label:string;disabled:boolean;onSave:(value:string)=>void}){
 const [draft,setDraft]=useState(value||'');const cancelled=useRef(false);useEffect(()=>setDraft(value||''),[value]);
 return <input aria-label={label} disabled={disabled} value={draft} placeholder="—" onFocus={()=>{cancelled.current=false}} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(!cancelled.current&&draft!==(value||''))onSave(draft)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.stopPropagation();cancelled.current=true;setDraft(value||'');e.currentTarget.blur()}}}/>;
}

export function ClientBoard({query='',onBack}:{query?:string;onBack?:()=>void}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');
 const [search,setSearch]=useState(query),[type,setType]=useState(''),[sort,setSort]=useState('manual'),[archived,setArchived]=useState(false);
 const [collapsed,setCollapsed]=useState<string[]>([]),[hidden,setHidden]=useState<Field[]>(['company','fiscal_data']),[selected,setSelected]=useState<string[]>([]);
 const [drawer,setDrawer]=useState<string|null>(null),[newGroup,setNewGroup]=useState(false),[groupName,setGroupName]=useState('');
 const [newClient,setNewClient]=useState<string|null>(null),[clientName,setClientName]=useState('');
 const [boardId,setBoardId]=useState<string|null>(null);
 const [dragId,setDragId]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/client-board',{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body);setError('');return true}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el tablero.');return false}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load()};window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[load]);
 async function mutate(body:unknown){if(busy)return false;setBusy(true);setError('');setSaved('');try{const r=await fetch('/api/client-board',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error);const refreshed=await load();setSaved(refreshed?'Guardado en el espacio compartido':'');return refreshed}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');return false}finally{setBusy(false)}}
 const update=(ids:string[],patch:Record<string,unknown>)=>mutate({action:'update',ids,patch});
 const visible=useMemo(()=>data.clients.filter(c=>Boolean(c.deleted_at)===archived&&(!type||c.client_type===type)&&`${c.company_name} ${columns.map(([k])=>c[k]||'').join(' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.company_name.localeCompare(b.company_name,'es'):sort==='city'?(a.city||'').localeCompare(b.city||'','es'):a.position-b.position),[data,search,query,type,sort,archived]);
 useEffect(()=>setSearch(query),[query]);
 const activeBoard=data.groups.find(g=>g.id===(boardId??data.groups[0]?.id));
 const boardGroups=boardId==='all'?data.groups:activeBoard?[activeBoard]:[];
 const chooseBoard=(id:string)=>{setBoardId(id);setSelected([]);setSearch('');setType('');setDrawer(null);setSaved('')};
 const current=data.clients.find(c=>c.id===drawer);
 const types=Array.from(new Set(data.clients.map(c=>c.client_type))).filter(Boolean).sort();
 const move=(ids:string[],groupId:string,position?:number)=>update(ids,{group_id:groupId,position:position??Math.max(0,...data.clients.filter(c=>c.group_id===groupId).map(c=>c.position))+1000});
 const reorderGroup=(g:Group,direction:number)=>{const i=data.groups.findIndex(x=>x.id===g.id),target=data.groups[i+direction];if(!target)return;const beyond=data.groups[i+direction*2];const position=direction<0?(target.position+(beyond?.position??target.position-2000))/2:(target.position+(beyond?.position??target.position+2000))/2;void mutate({action:'group',...g,position})};
 const openCreate=(id:string)=>{setClientName('');setNewClient(id)};
 return <section className="cb-board">
  <header className="cb-title"><div><p>PERFORMANCE LAB / BASE DE DATOS</p><h1>{boardId==='all'?'Todos los clientes':activeBoard?.name||'Clientes'} <Users size={24}/></h1><span>{data.clients.filter(c=>!c.deleted_at&&(boardId==='all'||c.group_id===activeBoard?.id)).length} registros · Clientes</span></div>{onBack&&<button onClick={onBack}>Volver a Mi día</button>}</header>
  <nav className="cb-board-nav" aria-label="Tableros de clientes">{data.groups.map(g=><button key={g.id} aria-current={activeBoard?.id===g.id?'page':undefined} className={activeBoard?.id===g.id?'active':''} onClick={()=>chooseBoard(g.id)} onDragOver={e=>{if(dragId)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(dragId)void move([dragId],g.id);setDragId(null)}}><i style={{background:g.color}}/>{g.name}<span>{data.clients.filter(c=>!c.deleted_at&&c.group_id===g.id).length}</span></button>)}<button className={boardId==='all'?'active':''} aria-current={boardId==='all'?'page':undefined} onClick={()=>chooseBoard('all')}>Todos los clientes</button></nav>
  <div className="cb-tabs"><button className={!archived?'active':''} onClick={()=>{setArchived(false);setSelected([])}}>Tabla principal</button><button className={archived?'active':''} onClick={()=>{setArchived(true);setSelected([])}}><Archive size={15}/> Archivados</button></div>
  <div className="cb-toolbar"><button className="cb-primary" disabled={!data.canEdit||busy||!data.groups.length} onClick={()=>openCreate(activeBoard?.id??data.groups[0].id)}><Plus size={16}/> Nuevo cliente</button><button disabled={!data.canEdit||busy} onClick={()=>setNewGroup(true)}>+ Tablero</button><label className="cb-search"><Search size={16}/><input aria-label="Buscar clientes" placeholder="Buscar clientes o contactos" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrar tipo de cliente" value={type} onChange={e=>setType(e.target.value)}><option value="">Todos los tipos</option>{types.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Ordenar clientes" value={sort} onChange={e=>setSort(e.target.value)}><option value="manual">Orden manual</option><option value="name">Nombre A–Z</option><option value="city">Ciudad A–Z</option></select><details className="cb-columns"><summary><Columns3 size={16}/> Columnas</summary><div>{columns.map(([key,title])=><label key={key}><input type="checkbox" checked={!hidden.includes(key)} onChange={()=>setHidden(v=>v.includes(key)?v.filter(k=>k!==key):[...v,key])}/>{title}</label>)}</div></details><button aria-label="Actualizar tablero" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/></button></div>
  <div aria-live="polite" className="cb-feedback">{busy?'Guardando…':saved||'Arrastra una fila para moverla. También puedes seleccionar varias y elegir otro tablero.'}</div>
  {error&&<div role="alert" className="cb-error">{error} <a href="/auth">Abrir inicio de sesión</a></div>}
  {selected.length>0&&<div className="cb-bulk"><b>{selected.length} seleccionados</b><select aria-label="Mover seleccionados a tablero" value="" disabled={busy} onChange={async e=>{if(await move(selected,e.target.value))setSelected([])}}><option value="" disabled>Mover a…</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button disabled={busy} onClick={async()=>{if(await update(selected,{deleted_at:archived?null:new Date().toISOString()}))setSelected([])}}>{archived?'Restaurar':'Archivar'}</button><button onClick={()=>setSelected([])}>Cancelar selección</button></div>}
  {loading?<p>Cargando clientes compartidos…</p>:boardGroups.map((group)=>{
   const gi=data.groups.findIndex(g=>g.id===group.id);
   const members=visible.filter(c=>c.group_id===group.id),isClosed=collapsed.includes(group.id);
   return <section key={group.id} className={'cb-group '+(dragId?'cb-drop-target':'')} style={{'--group-color':group.color} as React.CSSProperties} onDragOver={e=>{if(dragId)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(dragId)void move([dragId],group.id);setDragId(null)}}>
    <header><button className="cb-group-name" aria-expanded={!isClosed} onClick={()=>setCollapsed(v=>isClosed?v.filter(x=>x!==group.id):[...v,group.id])}>{isClosed?<ChevronRight size={20}/>:<ChevronDown size={20}/>}<h2>{group.name}</h2><span>{members.length}</span></button><div className="cb-group-tools"><button aria-label={'Subir grupo '+group.name} disabled={busy||!data.canEdit||gi===0} onClick={()=>reorderGroup(group,-1)}><ArrowUp size={15}/></button><button aria-label={'Bajar grupo '+group.name} disabled={busy||!data.canEdit||gi===data.groups.length-1} onClick={()=>reorderGroup(group,1)}><ArrowDown size={15}/></button></div></header>
    {!isClosed&&<div className="cb-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label={'Seleccionar grupo '+group.name} disabled={!data.canEdit||!members.length} checked={members.length>0&&members.every(c=>selected.includes(c.id))} onChange={e=>setSelected(v=>e.target.checked?Array.from(new Set([...v,...members.map(c=>c.id)])):v.filter(id=>!members.some(c=>c.id===id)))}/></th><th>Cliente</th>{columns.filter(([k])=>!hidden.includes(k)).map(([k,title])=><th key={k}>{title}</th>)}<th>Eventos</th><th>Mover a</th></tr></thead><tbody>{members.map((client,index)=><tr key={client.id} draggable={data.canEdit&&!busy&&sort==='manual'} onDragStart={e=>{setDragId(client.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',client.id)}} onDragEnd={()=>setDragId(null)} onDragOver={e=>{if(dragId)e.preventDefault()}} onDrop={e=>{e.preventDefault();e.stopPropagation();if(dragId&&dragId!==client.id)void move([dragId],group.id,((members[index-1]?.position??client.position-2000)+client.position)/2);setDragId(null)}}>
     <td><input aria-label={'Seleccionar '+client.company_name} type="checkbox" disabled={!data.canEdit} checked={selected.includes(client.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,client.id]:v.filter(x=>x!==client.id))}/></td><td className="cb-name-cell"><GripVertical size={14}/><button title={client.company_name} onClick={()=>setDrawer(client.id)}>{client.company_name}</button></td>{columns.filter(([k])=>!hidden.includes(k)).map(([key,label])=><td key={key}>{key==='client_type'?<select aria-label={label+' de '+client.company_name} disabled={!data.canEdit||busy} value={client.client_type} onChange={e=>void update([client.id],{client_type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select>:<Cell value={client[key]} label={label+' de '+client.company_name} disabled={!data.canEdit||busy} onSave={v=>void update([client.id],{[key]:v})}/>}</td>)}<td><button className="cb-linked" onClick={()=>setDrawer(client.id)}>{data.events.filter(e=>e.client_id===client.id).length} trabajos</button></td><td><select aria-label={'Mover '+client.company_name} disabled={!data.canEdit||busy} value={group.id} onChange={e=>void move([client.id],e.target.value)}>{data.groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></td>
    </tr>)}</tbody></table>{!archived&&<button className="cb-add-row" disabled={!data.canEdit||busy} onClick={()=>openCreate(group.id)}>+ Añadir cliente en {group.name}</button>}{!members.length&&<p className="cb-empty">{search||type?'Ningún cliente coincide con los filtros.':'No hay clientes en este grupo.'}</p>}</div>}
   </section>
  })}
  <Dialog.Root open={Boolean(current)} onOpenChange={v=>{if(!v)setDrawer(null)}}><Dialog.Portal><Dialog.Overlay className="cb-overlay"/><Dialog.Content className="cb-drawer"><Dialog.Title>{current?.company_name}</Dialog.Title><Dialog.Description>Ficha de cliente · cambios compartidos con el equipo</Dialog.Description>{error&&<p role="alert" className="cb-error">{error}</p>}<p aria-live="polite">{busy?'Guardando…':saved}</p><Dialog.Close className="cb-close" aria-label="Cerrar ficha"><X size={20}/></Dialog.Close>{current&&<><label>Nombre<Cell value={current.company_name} label="Nombre del cliente" disabled={!data.canEdit||busy} onSave={v=>void update([current.id],{company_name:v})}/></label>{columns.map(([key,label])=><label key={key}>{label}<Cell value={current[key]} label={label} disabled={!data.canEdit||busy} onSave={v=>void update([current.id],{[key]:v})}/></label>)}<label>Notas<Cell value={current.notes} label="Notas del cliente" disabled={!data.canEdit||busy} onSave={v=>void update([current.id],{notes:v})}/></label><h3>Eventos vinculados</h3>{data.events.filter(e=>e.client_id===current.id).map(e=><article className="cb-event" key={e.id}><b>{e.event_name}</b><span>{e.event_date?new Date(e.event_date+'T12:00:00').toLocaleDateString('es-ES'):'Sin fecha'} · {e.venue||'Sin venue'}</span><small>{e.status}</small></article>)}{!data.events.some(e=>e.client_id===current.id)&&<p>Este cliente todavía no tiene eventos vinculados.</p>}<select aria-label="Vincular evento sin cliente" value="" disabled={busy||!data.canLinkEvents} onChange={e=>void mutate({action:'linkEvent',event_id:e.target.value,client_id:current.id})}><option value="" disabled>+ Vincular un evento sin cliente</option>{data.events.filter(e=>!e.client_id&&(e.event_date||e.venue||e.event_name.trim()!=='Evento')).map(e=><option key={e.id} value={e.id}>{e.event_date||'Sin fecha'} · {e.event_name}</option>)}</select>{current.monday_source&&<p className="cb-source">Copiado de Monday · grupo original: {String(current.monday_source.group)} · fila {String(current.monday_source.source_row)}</p>}<button disabled={busy||!data.canEdit} onClick={async()=>{if(await update([current.id],{deleted_at:current.deleted_at?null:new Date().toISOString()}))setDrawer(null)}}>{current.deleted_at?'Restaurar cliente':'Archivar cliente'}</button></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  <Dialog.Root open={Boolean(newClient)} onOpenChange={v=>{if(!v)setNewClient(null)}}><Dialog.Portal><Dialog.Overlay className="cb-overlay"/><Dialog.Content className="cb-modal"><Dialog.Title>Nuevo cliente</Dialog.Title><Dialog.Description>Se guardará en {data.groups.find(g=>g.id===newClient)?.name}.</Dialog.Description>{error&&<p role="alert" className="cb-error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'create',patch:{company_name:clientName,group_id:newClient,client_type:'Sin clasificar',position:Math.max(0,...data.clients.filter(c=>c.group_id===newClient).map(c=>c.position))+1000}}))setNewClient(null)}}><label>Nombre del cliente<input autoFocus required maxLength={200} value={clientName} onChange={e=>setClientName(e.target.value)}/></label><button className="cb-primary" disabled={busy}>Guardar cliente</button></form><Dialog.Close className="cb-close" aria-label="Cerrar"><X size={20}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
  <Dialog.Root open={newGroup} onOpenChange={setNewGroup}><Dialog.Portal><Dialog.Overlay className="cb-overlay"/><Dialog.Content className="cb-modal"><Dialog.Title>Nuevo tablero</Dialog.Title><Dialog.Description>Organiza los clientes por mercado, ciudad o equipo.</Dialog.Description>{error&&<p role="alert" className="cb-error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'group',name:groupName,position:Math.max(0,...data.groups.map(g=>g.position))+1000,color:'#0073ea'})){setNewGroup(false);setGroupName('')}}}><label>Nombre del tablero<input required maxLength={120} value={groupName} onChange={e=>setGroupName(e.target.value)}/></label><button className="cb-primary" disabled={busy}>Crear tablero</button></form><Dialog.Close className="cb-close" aria-label="Cerrar"><X size={20}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 </section>;
}
