'use client';
import {useEffect,useRef,useState} from 'react';
import {responseJson} from '@/lib/response-json';
import './invoices.css';
type Document={id:string;filename:string;size_bytes:number;created_at:string;status:string;invoice_id:string|null;expense_id:string|null;notes:string;extracted_data?:{number:string;total_cents:number;currency:string;recipient:{name:string};warnings:string[]};processed_at?:string};
type Entry={file:File;status:string;error:boolean};
export function DocumentInbox({onManual}:{onManual:()=>void}){
 const [documents,setDocuments]=useState<Document[]>([]),[queue,setQueue]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Document>(),[search,setSearch]=useState('');const input=useRef<HTMLInputElement>(null),lock=useRef(false);
 async function load(){try{const r=await fetch('/api/financial-documents',{cache:'no-store'}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setDocuments(d.documents);setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar')}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!busy)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[busy]);
 async function upload(files:File[]){if(lock.current||!files.length)return;lock.current=true;setBusy(true);setQueue(files.map(file=>({file,status:'En cola',error:false})));try{for(let i=0;i<files.length;i++){setQueue(q=>q.map((e,n)=>n===i?{...e,status:'Subiendo…'}:e));try{const f=new FormData();f.set('file',files[i]);const r=await fetch('/api/financial-documents',{method:'POST',body:f}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setQueue(q=>q.map((e,n)=>n===i?{...e,status:d.duplicate?'Ya existía · no duplicado':'Guardado · ficha creada'}:e))}catch(e){setQueue(q=>q.map((v,n)=>n===i?{...v,error:true,status:e instanceof Error?e.message:'Error al subir'}:v))}}await load()}finally{lock.current=false;setBusy(false)}}
 return <section className="inv-related"><header className="module-head"><div><h2>Facturas &amp; Documentos</h2><p>Selecciona varios archivos: cada documento tendrá su propia ficha.</p></div><button className="primary-button" disabled={busy} onClick={()=>input.current?.click()}>Subir facturas</button></header><input ref={input} type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.heic,.heif" hidden onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value=''}}/><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(Array.from(e.dataTransfer.files))}} style={{border:'2px dashed #b3a6ec',borderRadius:12,padding:24,margin:'16px 0',textAlign:'center'}}><button disabled={busy} className="secondary-button" onClick={()=>input.current?.click()}>{busy?'Guardando archivos…':'Seleccionar archivos o arrastrarlos aquí'}</button><p>PDF, JPG, PNG y HEIC · máximo 20 MB por archivo · originales privados</p><p>Los documentos quedan pendientes de revisión. La extracción de nuevas subidas no es automática todavía. Las fichas procesadas muestran su factura vinculada.</p></div>{queue.length>0&&<div aria-live="polite"><p>{queue.filter(e=>e.status.startsWith('Guardado')||e.status.startsWith('Ya existía')).length} de {queue.length} procesados</p>{queue.map((e,i)=><p key={i} style={{color:e.error?'#bd283e':undefined}}>{e.file.name} · {e.status}</p>)}{!busy&&queue.some(e=>e.error)&&<button onClick={()=>void upload(queue.filter(e=>e.error).map(e=>e.file))}>Reintentar archivos fallidos</button>}</div>}{error&&<p role="alert">{error}<button onClick={()=>void load()}>Reintentar</button></p>}<div className="crm-toolbar"><input aria-label="Buscar documentos" placeholder="Buscar por nombre de archivo" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={onManual}>Crear factura manualmente</button><button onClick={()=>void load()}>Actualizar</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Documento</th><th>Subido</th><th>Tamaño</th><th>Estado</th><th>Original</th></tr></thead><tbody>{documents.filter(d=>d.filename.toLowerCase().includes(search.toLowerCase())).map(d=><tr key={d.id}><td><button className="text-button" onClick={()=>setSelected(d)}>{d.filename}</button></td><td>{new Date(d.created_at).toLocaleString('es-ES')}</td><td>{(d.size_bytes/1024/1024).toFixed(2)} MB</td><td>{d.extracted_data?'Datos extraídos':d.status==='linked'?'Vinculado':'Pendiente de revisión'}</td><td><a href={'/api/financial-documents?id='+d.id} target="_blank" rel="noreferrer">Descargar original</a></td></tr>)}</tbody></table>{!documents.length&&<p>Aún no hay documentos subidos.</p>}</div>{selected&&<DocumentCard document={selected} close={()=>setSelected(undefined)} saved={load}/>}</section>
}
function DocumentCard({document:d,close,saved}:{document:Document;close:()=>void;saved:()=>Promise<void>}){const ref=useRef<HTMLDialogElement>(null),[invoice,setInvoice]=useState(d.invoice_id||''),[expense,setExpense]=useState(d.expense_id||''),[notes,setNotes]=useState(d.notes),[busy,setBusy]=useState(false),[error,setError]=useState(''),[invoices,setInvoices]=useState<{id:string;number:string;concept:string}[]>([]),[expenses,setExpenses]=useState<{id:string;concept:string;number:string}[]>([]);
 useEffect(()=>{ref.current?.showModal();Promise.all(['/api/invoices','/api/expenses'].map(async u=>{const r=await fetch(u),j=await responseJson(r);if(!r.ok)throw Error(j.error);return j})).then(([i,e])=>{setInvoices(i.invoices);setExpenses(e.expenses)}).catch(e=>setError(e.message))},[]);
 return <dialog ref={ref} className="crm-dialog" onCancel={e=>{if(busy)e.preventDefault();else close()}}><header><h2>{d.filename}</h2><button disabled={busy} onClick={close}>Cerrar</button></header><p>Original guardado el {new Date(d.created_at).toLocaleString('es-ES')}</p><a href={'/api/financial-documents?id='+d.id} target="_blank" rel="noreferrer">Descargar original</a>{d.extracted_data&&<section><h3>Datos extraídos</h3><p>Factura {d.extracted_data.number} · {d.extracted_data.recipient.name}</p><strong>{new Intl.NumberFormat('es-ES',{style:'currency',currency:d.extracted_data.currency}).format(d.extracted_data.total_cents/100)}</strong>{d.extracted_data.warnings.map((w,i)=><p key={i}>{w}</p>)}</section>}<p>Revisa el documento y vincúlalo a la factura o gasto correspondiente. Esta acción no registra pagos.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await fetch('/api/financial-documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id,invoice_id:invoice||null,expense_id:expense||null,notes})}),j=await responseJson(r);if(!r.ok)throw Error(j.error);await saved();close()}catch(e){setError(e instanceof Error?e.message:'Error al guardar')}finally{setBusy(false)}}}><fieldset disabled={busy}><label>Factura emitida<select value={invoice} onChange={e=>{setInvoice(e.target.value);if(e.target.value)setExpense('')}}><option value="">Sin vincular</option>{invoices.map(i=><option key={i.id} value={i.id}>{i.number} · {i.concept}</option>)}</select></label><label>Gasto / factura recibida<select value={expense} onChange={e=>{setExpense(e.target.value);if(e.target.value)setInvoice('')}}><option value="">Sin vincular</option>{expenses.map(e=><option key={e.id} value={e.id}>{e.number||'Sin nº'} · {e.concept}</option>)}</select></label><label>Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary-button">Guardar ficha</button></fieldset></form>{invoice&&<a href={`/?invoice=${invoice}#facturas`}>Abrir factura</a>}{expense&&<a href={`/?expense=${expense}#facturas`}>Abrir gasto</a>}</dialog>
}
