'use client';
import {useState} from 'react';
import {responseJson} from '@/lib/response-json';
import type {KitDocument} from '@/lib/show-kit';
type Pack={canShare:boolean;talents:{id:string;real_name:string}[];event:{event_name:string;event_date:string;venue:string};shows:{id:string;name:string}[];links:{show_id:string;quantity:number}[];items:(KitDocument['items'][number]&{show_id:string})[];checks:{show_id:string;label:string}[];missing:{show_id:string}[];checked:Record<string,boolean>;version:number|null};
export function EventShowKit({eventId}:{eventId:string}){
 const [pack,setPack]=useState<Pack>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/show-kit/event?event='+eventId),d=await responseJson(r);if(!r.ok)throw Error(d.error);setPack(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Error de conexión');}finally{setBusy(false);}}
 async function check(key:string,value:boolean){if(!pack)return;setBusy(true);try{const checked={...pack.checked,[key]:value},r=await fetch('/api/show-kit/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,version:pack.version,checked})}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setPack({...pack,checked,version:d.version});setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}}
 const [artist,setArtist]=useState(''),[shareUrl,setShareUrl]=useState('');
 async function share(showId:string){setBusy(true);try{const r=await fetch('/api/show-kit/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({show_id:showId,event_id:eventId,talent_id:artist,audience:'artist'})}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setShareUrl(location.origin+d.path);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo generar');}finally{setBusy(false);}}
 const name=(id:string)=>pack?.shows.find(s=>s.id===id)?.name||'Show';
 return <section><h3>Material comercial y preparación</h3><button disabled={busy} onClick={()=>void load()}>Generar / actualizar packing list y briefs</button>{error&&<p role="alert">{error}</p>}{pack&&<><p>{pack.event.event_name} · {pack.event.event_date} · {pack.event.venue}</p>{!pack.links.length&&<p>Vincula primero los shows del evento.</p>}{pack.canShare&&<label>Preparar brief para<select value={artist} onChange={e=>setArtist(e.target.value)}><option value="">Selecciona un artista del evento</option>{pack.talents.map(t=><option key={t.id} value={t.id}>{t.real_name}</option>)}</select></label>}{shareUrl&&<p><a href={shareUrl} target="_blank" rel="noreferrer">Abrir brief de artista · válido 7 días</a><input aria-label="Enlace para WhatsApp" readOnly value={shareUrl} onFocus={e=>e.target.select()}/></p>}{pack.links.map(l=><p key={l.show_id}>{l.quantity} × {name(l.show_id)} · <a href={`/?show=${l.show_id}#shows`}>Abrir Sales Kit / brief del artista</a> · <a href={`/?quoteShow=${l.show_id}#propuestas`}>Crear propuesta</a>{pack.canShare&&<button disabled={busy||!artist} onClick={()=>void share(l.show_id)}>Generar brief para este artista</button>}</p>)}{pack.missing.map(m=><p key={m.show_id} role="status">Falta completar el kit de {name(m.show_id)}.</p>)}<p>Esta lista prepara el material; no reserva ni modifica existencias.</p>{pack.items.map(item=>{const key=item.show_id+':'+item.id+':'+item.quantity;return <label key={key} style={{display:'flex',gap:10,alignItems:'center',padding:10,borderBottom:'1px solid #ddd'}}><input type="checkbox" disabled={busy} checked={!!pack.checked[key]} onChange={e=>void check(key,e.target.checked)}/>{item.image&&<img src={item.image} alt="" width={55} height={55} style={{objectFit:'cover'}}/>}<span><strong>{item.quantity} × {item.name}</strong> — {item.location} / {item.box}<small style={{display:'block'}}>{name(item.show_id)} · {item.size} · {item.required?'Obligatorio':'Opcional'} · {item.condition}</small>{item.notes}</span></label>;})}<h4>Comprobar antes de salir</h4>{pack.checks.map(c=>{const key=c.show_id+':check:'+c.label;return <label key={key} style={{display:'block'}}><input type="checkbox" disabled={busy} checked={!!pack.checked[key]} onChange={e=>void check(key,e.target.checked)}/>{name(c.show_id)} · {c.label}</label>;})}</>}</section>;
}
