'use client';
import {responseJson} from '@/lib/response-json';
import {useEffect,useState} from 'react';
import {eventMoney,moneyTotals,euros,type MoneyEvent} from '@/lib/event-money';
import './finance.css';
export function FinanceSummary({events}:{events?:MoneyEvent[]}){
 const [stored,setStored]=useState<MoneyEvent[]>([]),[period,setPeriod]=useState('all'),[error,setError]=useState(''),[ready,setReady]=useState(Boolean(events));
 useEffect(()=>{if(events)return;let alive=true;async function load(){try{const r=await fetch('/api/event-board',{cache:'no-store'});const d=await responseJson(r);if(!r.ok)throw Error(d.error);if(alive){setStored(d.events);setError('');setReady(true)}}catch(e){if(alive)setError(e instanceof Error?e.message:'No se pudieron cargar los importes.')}}void load();window.addEventListener('focus',load);return()=>{alive=false;window.removeEventListener('focus',load)}},[events]);
 const all=(events??stored).filter(e=>!e.deleted_at&&e.status!=='cancelled'&&(e.event_date||e.income_cents!==null||e.expenses_cents!==null));const months=[...new Set(all.map(e=>e.event_date?.slice(0,7)).filter((x):x is string=>Boolean(x)))].sort().reverse();const selected=all.filter(e=>period==='all'||(period==='undated'?!e.event_date:e.event_date?.startsWith(period)));const t=moneyTotals(selected);
  return <section className="fin-summary"><header><div><h2>Economía de los eventos</h2><p>Por fecha del evento · excluye archivados y cancelados</p></div><select aria-label="Periodo económico" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Total general</option>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00').toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</option>)}<option value="undated">Sin fecha</option></select></header>{error?<p role="alert">{error}</p>:!ready&&!events?<p>Cargando importes…</p>:<><div className="fin-cards">{[['Ingreso total',euros(t.income)],['Coste total',euros(t.cost)],['Beneficio bruto',euros(t.profit)],['Margen',t.margin===null?'—':t.margin.toFixed(1)+' %'],['Cobrado',euros(t.paid)],['Pendiente de cobro',euros(t.pending)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p style={{fontSize:'13px',margin:'8px 0 4px',color:'#374151'}}><strong>Facturado:</strong> {euros(t.invoiced)} · <strong>Cash:</strong> {euros(t.cash)} · <strong>Total Income:</strong> {euros(t.invoiced+t.cash)}</p><p>{selected.length} eventos · {t.incomplete} con importes por completar.{t.unknown>0?' Cobro sin confirmar: '+euros(t.unknown)+'.':''} Los campos vacíos no aportan importe al total. Margen calculado sobre ingresos totales.</p><details><summary>Desglose mensual</summary><div className="fin-scroll"><table><thead><tr>{['Mes','Eventos','Ingresos','Gastos','Otros gastos','Coste total','Beneficio bruto','Margen','Cobrado','Pendiente'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{[...months,...(all.some(e=>!e.event_date)?['undated']:[])].map(m=>{const rows=all.filter(e=>m==='undated'?!e.event_date:e.event_date?.startsWith(m));const v=moneyTotals(rows);return <tr key={m}><td>{m==='undated'?'Sin fecha':m}</td><td>{rows.length}</td><td>{euros(v.income)}</td><td>{euros(rows.reduce((a,e)=>a+(e.expenses_cents??0),0))}</td><td>{euros(rows.reduce((a,e)=>a+(e.other_expenses_cents??0),0))}</td><td>{euros(v.cost)}</td><td>{euros(v.profit)}</td><td>{v.margin===null?'—':v.margin.toFixed(1)+' %'}</td><td>{euros(v.paid)}</td><td>{euros(v.pending)}</td></tr>})}</tbody></table></div></details></>}</section>;
}
