'use client';
import {ChatGPTContextButton} from '@/components/chatgpt-context-button';
import {useCallback,useEffect,useRef,useState} from 'react';
import {newProposal,newOption,newLine,proposalSchema,proposalStatuses,quoteUnits,optionMoney,money,proposalText,priceReferences,type Proposal,type ProposalFields,type QuoteLine} from '@/lib/proposals';
import type {WorkspaceReferences} from '@/lib/server/workspace-data';
import {responseJson} from '@/lib/response-json';
import './sales-workspace.css';
type Data={data:Proposal[];refs:WorkspaceReferences;canEdit:boolean};
export function ProposalsWorkspace({query=''}:{query?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[archived,setArchived]=useState(false),[notice,setNotice]=useState(''),[tab,setTab]=useState('details'),[showSearch,setShowSearch]=useState('');
 const [editing,setEditing]=useState<{id:string;version?:number;code?:string;event_id?:string|null;fields:ProposalFields}|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),snapshot=useRef('');
 const close=()=>{if(busy)return;if(editing&&JSON.stringify(editing.fields)!==snapshot.current&&!window.confirm('Hay cambios sin guardar. ¿Quieres descartarlos?'))return;setEditing(null);};
 const load=useCallback(async()=>{try{const r=await fetch('/api/proposals',{cache:'no-store'}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setData(d);setError('');return d as Data;}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las propuestas.');return null;}},[]);
 useEffect(()=>{void load();window.addEventListener('focus',load);return()=>window.removeEventListener('focus',load);},[load]);
 useEffect(()=>{if(editing)dialog.current?.showModal();else dialog.current?.close();},[editing]);
 function open(p?:Proposal,duplicate=false){setError('');setNotice('');setTab('details');setEditing({id:duplicate||!p?crypto.randomUUID():p.id,version:duplicate?undefined:p?.version,code:duplicate?undefined:p?.proposal_code,event_id:duplicate?null:p?.event_id,fields:p?{...p,title:duplicate?p.title+' · copia':p.title,status:duplicate?'draft':p.status,selected_option_id:duplicate?'':p.selected_option_id}:newProposal()});snapshot.current=p?JSON.stringify({...p,title:duplicate?p.title+' · copia':p.title,status:duplicate?'draft':p.status,selected_option_id:duplicate?'':p.selected_option_id}):'';}
 useEffect(()=>{if(!data)return;const url=new URL(window.location.href),id=url.searchParams.get('proposal');if(id){const p=data.data.find(p=>p.id===id);if(p)open(p);url.searchParams.delete('proposal');window.history.replaceState(null,'',url);}const showId=url.searchParams.get('quoteShow');if(showId){const show=data.refs.shows.find(s=>s.id===showId);if(show){const fields=newProposal();const option=newOption();const line=newLine();line.show_ids=[show.id];line.label=show.name;line.description=show.description||'';option.lines=[line];fields.options=[option];fields.title=show.name;setEditing({id:crypto.randomUUID(),fields});}url.searchParams.delete('quoteShow');window.history.replaceState(null,'',url);}const opId=url.searchParams.get('quoteOpportunity');if(opId){const op=data.refs.opportunities.find(o=>o.id===opId);if(op){setEditing({id:crypto.randomUUID(),fields:{...newProposal(),title:op.title,opportunity_id:op.id,client_id:op.client_id||'',client_name:data.refs.clients.find(c=>c.id===op.client_id)?.company_name||'',event_date:op.event_date||'',city:op.city||'',venue:op.venue||''}});}url.searchParams.delete('quoteOpportunity');window.history.replaceState(null,'',url);}},[data]);
 const field=<K extends keyof ProposalFields>(key:K,value:ProposalFields[K])=>setEditing(e=>e?{...e,fields:{...e.fields,[key]:value}}:null);
 function lineField(optionId:string,lineId:string,patch:Partial<QuoteLine>){setEditing(e=>e?{...e,fields:{...e.fields,options:e.fields.options.map(o=>o.id===optionId?{...o,lines:o.lines.map(l=>l.id===lineId?{...l,...patch}:l)}:o)}}:null);}
 async function mutate(body:Record<string,unknown>){if(busy)return null;setBusy(true);setError('');try{const r=await fetch('/api/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await responseJson(r);if(!r.ok)throw Error(d.error);const latest=await load();return {...d,record:latest?.data.find(p=>p.id===body.id)};}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');return null;}finally{setBusy(false);}}
 async function save(){if(!editing)return false;const p=proposalSchema.safeParse(editing.fields);if(!p.success){setError(p.error.issues[0].message);return false;}const d=await mutate({id:editing.id,version:editing.version,fields:p.data});if(d){snapshot.current=JSON.stringify(p.data);setEditing(e=>e?{...e,version:d.version,code:e.code||'PL-'+e.id.slice(0,8).toUpperCase(),fields:p.data}:null);setNotice('Propuesta guardada para el equipo.');return true;}return false;}
 const validate=()=>{const p=proposalSchema.safeParse(editing?.fields);if(!p.success){setError(p.error.issues[0].message);return null;}return p.data;};
 async function pdf(){const q=validate();if(!q)return;setBusy(true);setError('');try{const r=await fetch('/api/proposals/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:q,code:editing?.code||''})});if(!r.ok){const d=await responseJson(r);throw Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=(editing?.code||'Performance-Lab-propuesta')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('PDF descargado con la versión que ves en la ficha.');}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el PDF.');}finally{setBusy(false);}}
 async function copy(){const q=validate();if(!q)return;try{await navigator.clipboard.writeText(proposalText(q,editing?.code));setNotice('Texto copiado para WhatsApp.');}catch{setTab('preview');setNotice('Selecciona el texto de la vista previa y cópialo.');}}
 const input=(key:'title'|'client_name'|'contact_name'|'event_date'|'city'|'venue'|'valid_until',label:string,type='text')=><label>{label}<input type={type} required={key==='title'} value={editing?.fields[key]||''} onChange={e=>field(key,e.target.value)}/></label>;
 const list=(data?.data||[]).filter(p=>archived?!!p.deleted_at:!p.deleted_at).filter(p=>(!status||p.status===status)&&(query+' '+search).toLowerCase().trim().split(/\s+/).every(s=>(p.title+' '+p.client_name+' '+p.proposal_code).toLowerCase().includes(s)));
 const q=editing?.fields;
 return <section className="sw-workspace"><header className="sw-heading"><div><p className="eyebrow">PERFORMANCE LAB · PROPUESTAS</p><h1>De una idea a un espectáculo.</h1><p>Presupuestos para tus clientes, con tu catálogo y tu forma de producir.</p></div><button className="primary-button" disabled={!data?.canEdit} onClick={()=>open()}>+ Nueva propuesta</button></header>
 <div className="sw-stats">{[['draft','Borradores'],['sent','Enviadas'],['follow_up','Seguimiento'],['accepted','Aceptadas']].map(([v,l])=><div key={v}><span>{l}</span><b>{data?.data.filter(p=>!p.deleted_at&&p.status===v).length||0}</b></div>)}</div>
 {error&&!editing&&<p className="sw-error" role="alert">{error} <button onClick={()=>void load()}>Reintentar</button></p>}
 <div className="sw-toolbar"><input aria-label="Buscar propuestas" placeholder="Cliente, nombre o referencia…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar por estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{proposalStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Archivadas</label><button onClick={()=>void load()}>Actualizar</button></div>
 <div className="sw-proposal-grid">{list.map(p=><article key={p.id} className="sw-proposal-card"><span className={'sw-pill '+p.status}>{proposalStatuses.find(s=>s[0]===p.status)?.[1]}</span><small>{p.proposal_code}</small><button className="sw-card-title" onClick={()=>open(p)}>{p.title}</button><p>{p.client_name||'Cliente por definir'} · {p.event_date||'Fecha por definir'}</p><p>{p.options.length} {p.options.length===1?'opción':'alternativas'} · {p.city||'Ciudad por definir'}</p><div className="sw-card-actions"><button onClick={()=>open(p)}>Abrir propuesta</button><button disabled={!data?.canEdit} onClick={()=>open(p,true)}>Duplicar</button><button disabled={busy||!data?.canEdit} onClick={()=>void mutate({id:p.id,version:p.version,action:p.deleted_at?'restore':'archive'})}>{p.deleted_at?'Restaurar':'Archivar'}</button></div></article>)}</div>{data&&!list.length&&<div className="sw-empty"><h2>Tu próxima propuesta empieza aquí.</h2><p>Añade un cliente, elige los shows y prepara el presupuesto en PDF o para WhatsApp.</p></div>}
 <dialog className="sw-dialog sw-quote-dialog" ref={dialog} onCancel={e=>{e.preventDefault();close();}}>{editing&&q&&<><header><div><p className="eyebrow">{editing.code||'NUEVA PROPUESTA'} · {editing.version?'GUARDADA':'SIN GUARDAR'}</p><h2>{q.title||'Diseñar una propuesta'}</h2></div><button disabled={busy} onClick={close} aria-label="Cerrar propuesta">✕</button></header>
 {editing.version&&<ChatGPTContextButton entityType="proposal" entityId={editing.id} disabled={busy||JSON.stringify(editing.fields)!==snapshot.current}/>}
 <nav className="sw-tabs">{[['details','1. Cliente y evento'],['budget','2. Shows y presupuesto'],['preview','3. Vista del cliente']].map(([v,l])=><button type="button" className={tab===v?'active':''} key={v} onClick={()=>setTab(v)}>{l}</button>)}</nav>
 {error&&<p className="sw-error" role="alert">{error}</p>}{notice&&<p className="sw-notice" role="status">{notice}</p>}
 <fieldset disabled={busy||!data?.canEdit}>
 {tab==='details'&&<><div className="sw-form-grid">{input('title','Nombre de la propuesta')}<label>Cliente de tu base<select value={q.client_id} onChange={e=>{const c=data?.refs.clients.find(c=>c.id===e.target.value);setEditing(v=>v?{...v,fields:{...v.fields,client_id:e.target.value,client_name:c?.company_name||v.fields.client_name}}:null);}}><option value="">Consulta nueva / sin cliente vinculado</option>{data?.refs.clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label>{input('client_name','Nombre del cliente en el presupuesto')}{input('contact_name','Persona de contacto')}{input('event_date','Fecha del evento','date')}{input('city','Ciudad')}{input('venue','Venue / lugar')}<label>Idioma del presupuesto<select value={q.language} onChange={e=>field('language',e.target.value as 'es'|'en')}><option value="es">Español</option><option value="en">English</option></select></label><label>Oportunidad vinculada<select value={q.opportunity_id} onChange={e=>{const op=data?.refs.opportunities.find(o=>o.id===e.target.value);setEditing(v=>v?{...v,fields:{...v.fields,opportunity_id:e.target.value,...(op?{client_id:op.client_id||'',client_name:data?.refs.clients.find(c=>c.id===op.client_id)?.company_name||v.fields.client_name,event_date:op.event_date||v.fields.event_date,city:op.city||v.fields.city,venue:op.venue||v.fields.venue}: {})}}:null);}}><option value="">Sin oportunidad</option>{data?.refs.opportunities.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Responsable<select value={q.owner_id} onChange={e=>field('owner_id',e.target.value)}><option value="">Sin asignar</option>{data?.refs.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><label>Concepto creativo para el cliente<textarea rows={4} placeholder="Qué propones, para qué momento del evento y qué experiencia quieres crear…" value={q.brief} onChange={e=>field('brief',e.target.value)}/></label><div className="sw-form-grid">{input('valid_until','Validez (solo si la has acordado)','date')}<label>IVA aplicable (%) · vacío = pendiente<input type="number" min={0} max={100} step="0.01" value={q.tax_percent??''} onChange={e=>field('tax_percent',e.target.value===''?null:Number(e.target.value))}/></label></div><label>Condiciones y logística para el cliente<textarea rows={4} placeholder="Viajes, alojamiento, técnica y condiciones que has confirmado o que siguen pendientes…" value={q.conditions} onChange={e=>field('conditions',e.target.value)}/></label><label className="sw-internal">Solo para el equipo · no sale en el presupuesto<textarea rows={3} value={q.internal_notes} onChange={e=>field('internal_notes',e.target.value)}/></label></>}
 {tab==='budget'&&<><div className="sw-help">Una partida puede incluir varios personajes con los mismos artistas. Los pases describen el servicio: no multiplican el precio. Las opciones son alternativas y no se suman.</div>{q.options.map((o,oi)=>{const m=optionMoney(o,q.tax_percent);return <section className="sw-option" key={o.id}><div className="sw-option-head"><label>Opción {oi+1}<input value={o.title} onChange={e=>field('options',q.options.map(x=>x.id===o.id?{...x,title:e.target.value}:x))}/></label><button disabled={q.options.length===1} onClick={()=>{field('options',q.options.filter(x=>x.id!==o.id));if(q.selected_option_id===o.id)field('selected_option_id','');}}>Eliminar opción</button></div>
 {o.lines.map((l,li)=><div className="sw-line" key={l.id}><div className="sw-line-heading"><b>Partida {li+1}</b><button onClick={()=>field('options',q.options.map(x=>x.id===o.id?{...x,lines:x.lines.filter(y=>y.id!==l.id)}:x))}>Quitar partida</button></div><div className="sw-form-grid"><label>Buscar en el catálogo<input placeholder="Nombre o categoría…" value={showSearch} onChange={e=>setShowSearch(e.target.value)}/></label><label>Añadir show / personaje<select value="" onChange={e=>{const show=data?.refs.shows.find(s=>s.id===e.target.value);if(show&&!l.show_ids.includes(show.id))lineField(o.id,l.id,{show_ids:[...l.show_ids,show.id],label:l.label?l.label+' + '+show.name:show.name,description:[l.description,show.description].filter(Boolean).join('\n\n')});}}><option value="">Elegir del catálogo real</option>{data?.refs.shows.filter(s=>(s.name+' '+s.category).toLowerCase().includes(showSearch.toLowerCase())&&!l.show_ids.includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.name}{s.category?' · '+s.category:''}</option>)}</select></label></div><div className="sw-chips">{l.show_ids.map(id=><button key={id} onClick={()=>lineField(o.id,l.id,{show_ids:l.show_ids.filter(s=>s!==id)})}>{data?.refs.shows.find(s=>s.id===id)?.name||'Show vinculado'} ×</button>)}</div><label>Nombre de la partida (también puedes escribir transporte, producción… )<input value={l.label} onChange={e=>lineField(o.id,l.id,{label:e.target.value})}/></label><label>Descripción para el cliente<textarea rows={2} value={l.description} onChange={e=>lineField(o.id,l.id,{description:e.target.value})}/></label><div className="sw-form-grid sw-four"><label>Cantidad<input type="number" min={1} max={1000} value={l.quantity} onChange={e=>lineField(o.id,l.id,{quantity:Number(e.target.value)})}/></label><label>Tarifa por<select value={l.unit} onChange={e=>lineField(o.id,l.id,{unit:e.target.value as QuoteLine['unit'],units:1})}>{quoteUnits.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Días / unidades<input disabled={l.unit==='package'||l.unit==='performer_event'} type="number" min={1} max={365} value={l.units} onChange={e=>lineField(o.id,l.id,{units:Number(e.target.value)})}/></label><label>Precio de venta / unidad (€)<input type="number" min={0} step="0.01" placeholder="Pendiente" value={l.unit_price_cents===null?'':l.unit_price_cents/100} onChange={e=>lineField(o.id,l.id,{unit_price_cents:e.target.value===''?null:Math.round(Number(e.target.value)*100),reference:false})}/></label></div>
 <details className="sw-reference"><summary>Usar una referencia habitual de Performance Lab</summary><p>Referencias aportadas por Manuel el 8/09/2026. Revisa alcance y vigencia para este caso. No son costes internos.</p><select aria-label="Referencia de precio" value="" onChange={e=>{const r=priceReferences[Number(e.target.value)];if(r){lineField(o.id,l.id,{unit_price_cents:r.cents,unit:r.unit,units:1,reference:true});setNotice(r.scope);}}}><option value="">Elegir referencia provisional</option>{priceReferences.map((r,i)=><option key={i} value={i}>{r.label}</option>)}</select></details>{l.reference&&<label className="sw-help"><input type="checkbox" checked={false} onChange={()=>lineField(o.id,l.id,{reference:false})}/> He revisado esta tarifa para este presupuesto; quitar «orientativo».</label>}
 <div className="sw-form-grid sw-four">{(['sets','duration','format','wardrobe'] as const).map((k,i)=><label key={k}>{['Pases incluidos','Duración / presencia','Formato (roaming, escenario…)','Cambios de vestuario'][i]}<input value={l[k]} onChange={e=>lineField(o.id,l.id,{[k]:e.target.value})}/></label>)}</div><details className="sw-internal"><summary>Coste interno y rentabilidad · solo equipo</summary><div className="sw-form-grid"><label>Coste (€) · vacío = desconocido<input type="number" min={0} step="0.01" value={l.internal_cost_cents===null?'':l.internal_cost_cents/100} onChange={e=>lineField(o.id,l.id,{internal_cost_cents:e.target.value===''?null:Math.round(Number(e.target.value)*100)})}/></label><label>El coste corresponde a<select value={l.cost_basis} onChange={e=>lineField(o.id,l.id,{cost_basis:e.target.value as QuoteLine['cost_basis']})}><option value="total">Toda esta partida / equipo</option><option value="unit">Cada unidad facturada</option></select></label></div></details></div>)}
 <button onClick={()=>field('options',q.options.map(x=>x.id===o.id?{...x,lines:[...x.lines,newLine()]}:x))}>+ Añadir show, paquete o extra</button><div className="sw-option-totals"><label>Descuento de esta opción (€)<input type="number" min={0} step="0.01" value={o.discount_cents/100} onChange={e=>field('options',q.options.map(x=>x.id===o.id?{...x,discount_cents:Math.round(Number(e.target.value)*100)}:x))}/></label><div><small>{m.complete?'Total antes de impuestos':'Subtotal conocido'}</small><strong>{money(m.net)}</strong><small>{m.total!==null?`Con IVA: ${money(m.total)}`:'Total final pendiente'}</small></div><div className="sw-internal"><small>Solo equipo · costes conocidos</small><b>{money(m.cost)}</b><small>{m.profit===null?'Beneficio pendiente de completar costes / precios':`Beneficio: ${money(m.profit)} · Margen: ${m.margin===null?'—':m.margin.toFixed(1)+'%'}`}</small></div></div></section>;})}<button onClick={()=>field('options',[...q.options,{...newOption(),title:'Alternativa '+(q.options.length+1)}])}>+ Añadir alternativa independiente</button></>}
 {tab==='preview'&&<><div className="sw-help">Así lo recibirá el cliente. Solo incluye venta, alcance y condiciones; las notas y costes internos quedan fuera. Cambiar el idioma traduce los rótulos; escribe también las descripciones y condiciones en el idioma del cliente.</div><textarea className="sw-public-preview" readOnly value={proposalText(q,editing.code)} aria-label="Texto para el cliente"/><div className="sw-card-actions"><button onClick={()=>void copy()}>Copiar texto para WhatsApp</button><button onClick={()=>void pdf()}>Descargar PDF</button></div></>}
 <div className="sw-form-grid sw-status-area"><label>Estado de la propuesta<select value={q.status} onChange={e=>field('status',e.target.value as ProposalFields['status'])}>{proposalStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Opción elegida por el cliente<select value={q.selected_option_id} onChange={e=>field('selected_option_id',e.target.value)}><option value="">Todavía sin elegir</option>{q.options.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label></div><p className="sw-fine">Los estados Enviada y Vista se registran manualmente. Descargar o copiar no envía la propuesta ni confirma su lectura.</p>
 <footer className="sw-sticky"><button className="primary-button" onClick={()=>void save()}>{busy?'Guardando…':'Guardar propuesta'}</button><button onClick={()=>void pdf()}>Descargar PDF</button><button onClick={()=>void copy()}>Copiar WhatsApp</button>{editing.version&&<a href={`/?taskProposal=${editing.id}#tareas`}>Crear tarea de seguimiento</a>}</footer>
 {editing.event_id?<a className="primary-button" href={`/?event=${editing.event_id}#eventos`}>Abrir evento vinculado</a>:q.status==='accepted'&&<div className="sw-help"><p>Guarda la aceptación y crea el evento con la opción elegida, su importe y sus shows. Requiere cliente de la base y fecha. Si la oportunidad ya tiene evento, se reutiliza.</p><button onClick={async()=>{if(!await save())return;const d=await mutate({id:editing.id,action:'create_event'});if(d){setEditing(e=>e?{...e,event_id:d.event_id,version:d.record?.version??e.version}:null);setNotice('Evento conectado. Puedes abrir su ficha.');}}}>Crear / abrir evento de esta propuesta</button></div>}
 </fieldset></>}</dialog></section>;
}
