'use client';
import {ShowShareLinks} from '@/components/show-share-links';
import {useEffect,useState} from 'react';
import {canReadSection,emptyDocument,fieldLabels,sectionNames,type Section,type KitDocument} from '@/lib/show-kit';
import {responseJson} from '@/lib/response-json';
import './show-kit.css';
type Show={id:string;name:string;category:string;description:string;public_url:string};
type Data={shows:Show[];sections:{show_id:string;section:Section;document:KitDocument;version:number}[];inventory:{id:string;name:string;main_image:string;default_location:string}[];role:string};
export function ShowKitWorkspace({query='',onAdd}:{query?:string;onAdd?:()=>void}){
 const [data,setData]=useState<Data>(),[selected,setSelected]=useState(''),[tab,setTab]=useState<Section|'overview'>('overview'),[search,setSearch]=useState(query),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[doc,setDoc]=useState<KitDocument>(emptyDocument()),[dirty,setDirty]=useState(false);
 async function load(){try{const r=await fetch('/api/show-kit',{cache:'no-store'}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setData(d);setError('');return d as Data;}catch(e){setError(e instanceof Error?e.message:'Error de conexión');}}
 useEffect(()=>{void load();const id=new URL(location.href).searchParams.get('show');if(id)setSelected(id);},[]);
 useEffect(()=>setSearch(query),[query]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const show=data?.shows.find(s=>s.id===selected);
 function select(id:string,next:Section|'overview'){if(dirty&&!confirm('Hay cambios sin guardar. ¿Descartarlos?'))return;setSelected(id);setTab(next);setDoc(structuredClone(data?.sections.find(s=>s.show_id===id&&s.section===next)?.document||emptyDocument()));setDirty(false);setNotice('');setShared(undefined);}
 function patch(value:Partial<KitDocument>){setDoc(d=>({...d,...value}));setDirty(true);}
 async function save(){setBusy(true);setError('');try{const record=data?.sections.find(s=>s.show_id===selected&&s.section===tab);const r=await fetch('/api/show-kit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({show_id:selected,section:tab,version:record?.version||null,document:doc})}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setDirty(false);await load();setNotice('Cambios guardados.');}catch(e){setError(e instanceof Error?e.message:'Error al guardar');}finally{setBusy(false);}}
 async function share(audience:'artist'|'client'){setBusy(true);try{const r=await fetch('/api/show-kit/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({show_id:selected,audience})}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setShared({id:d.id,url:location.origin+d.path});setNotice('Enlace creado con los datos guardados. Caduca en 7 días.');}catch(e){setError(e instanceof Error?e.message:'No se pudo compartir');}finally{setBusy(false);}}
 const [shared,setShared]=useState<{id:string;url:string}>();
 async function downloadPdf(){setBusy(true);setError('');try{const r=await fetch('/api/show-kit/pdf?show='+selected);if(!r.ok){const d=await responseJson(r);throw Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='Performance-Lab-ficha-tecnica.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'No se pudo descargar el PDF');}finally{setBusy(false);}}
 const copy=async(url:string)=>{try{await navigator.clipboard.writeText(url);setNotice('Enlace copiado.');}catch{setError('No se pudo copiar. Abre el enlace y cópialo de la barra de direcciones.');}};
 return <section className="sk-workspace"><header><div><p className="eyebrow">CATÁLOGO · SALES KIT · PRODUCCIÓN</p><h1>{show?.name||'Shows y personajes'}</h1><p>Una ficha maestra para vender, preparar y mantener cada show.</p></div>{!selected&&onAdd&&<button className="primary-button" onClick={onAdd}>Nuevo show</button>}{selected&&<button onClick={()=>select('','overview')}>← Catálogo</button>}</header>
 {error&&<p role="alert" className="sk-error">{error} <button onClick={()=>void load()}>Recargar</button></p>}{notice&&<p role="status">{notice}</p>}
 {!data&&!error&&<p>Cargando catálogo…</p>}
 {!selected&&data&&<><input aria-label="Buscar shows" placeholder="Buscar por nombre o categoría…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="sk-cards">{data.shows.filter(s=>(s.name+' '+s.category+' '+s.description).toLowerCase().includes(search.toLowerCase())).map(s=>{const hero=data.sections.find(k=>k.show_id===s.id&&k.section==='media')?.document.assets.find(a=>a.hero&&a.kind==='image');return <button className="sk-card" key={s.id} onClick={()=>select(s.id,'overview')}>{hero&&<img src={hero.url} alt=""/>}<small>{s.category}</small><h2>{s.name}</h2><p>{s.description||'Completa su ficha comercial y operativa.'}</p><strong>Abrir ficha →</strong></button>;})}</div></>}
 {show&&data&&<><nav aria-label="Pestañas del show"><button aria-pressed={tab==='overview'} onClick={()=>select(selected,'overview')}>Resumen</button>{(Object.keys(sectionNames) as Section[]).filter(s=>canReadSection(data.role,s)).map(s=><button key={s} aria-pressed={tab===s} onClick={()=>select(selected,s)}>{sectionNames[s]}</button>)}</nav>
 {tab==='overview'?<div className="sk-panel"><h2>{show.name}</h2><p>{show.description||'Sin descripción.'}</p><p>{show.category}</p><div className="sk-cards">{(Object.keys(sectionNames) as Section[]).filter(s=>canReadSection(data.role,s)).map(s=><button key={s} className="sk-card" onClick={()=>select(selected,s)}><h3>{sectionNames[s]}</h3><p>{data.sections.some(r=>r.show_id===selected&&r.section===s)?'Ficha guardada':'Pendiente de completar'}</p></button>)}</div></div>:<div className="sk-panel"><div className="sk-actions"><h2>{sectionNames[tab]}</h2><button className="primary-button" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'Guardando…':'Guardar cambios'}</button>{['sales','media'].includes(tab)&&<a href={`/?quoteShow=${selected}#propuestas`}>Añadir a propuesta</a>}{tab==='tech'&&<button disabled={busy||dirty} onClick={()=>void downloadPdf()}>Descargar ficha técnica PDF{dirty?' (guarda primero)':''}</button>}</div>
 {tab==='tech'&&<p>Solo para el cliente. No incluye precios, almacén ni instrucciones privadas.</p>}
 {['artist','tech','media'].includes(tab)&&<div className="sk-actions"><button disabled={busy||dirty} onClick={()=>void share(tab==='artist'?'artist':'client')}>Crear enlace {tab==='artist'?'para artista':'para cliente'} · 7 días</button>{shared&&<><a href={shared.url} target="_blank" rel="noreferrer">Abrir ficha compartida</a><button onClick={()=>void copy(shared.url)}>Copiar para WhatsApp</button><button onClick={async()=>{const r=await fetch('/api/show-kit/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revoke:shared.id})});if(r.ok){setShared(undefined);setNotice('Enlace revocado.');}else setError('No se pudo revocar el enlace.');}}>Revocar enlace</button></>}</div>}<fieldset disabled={busy}><div className="sk-fields">{Object.entries(fieldLabels[tab]).map(([k,label])=><label key={k}>{label}<textarea rows={3} value={doc.fields[k]||''} onChange={e=>patch({fields:{...doc.fields,[k]:e.target.value}})}/></label>)}</div>
 {tab==='media'&&<><button onClick={()=>patch({assets:[...doc.assets,{id:crypto.randomUUID(),label:'',url:'',kind:'image',hero:false,best:false,main:false,approved:false}]})}>+ Añadir foto, vídeo o enlace</button><div className="sk-cards">{doc.assets.map((a,i)=><div className="sk-card" key={a.id}>{a.kind==='image'&&/^https?:/.test(a.url)&&<img src={a.url} alt={a.label}/>}{a.kind==='video'&&a.url&&<a href={a.url} target="_blank" rel="noreferrer">Ver vídeo ↗</a>}<label>Nombre<input value={a.label} onChange={e=>patch({assets:doc.assets.map((v,j)=>j===i?{...v,label:e.target.value}:v)})}/></label><label>URL<input type="url" value={a.url} onChange={e=>patch({assets:doc.assets.map((v,j)=>j===i?{...v,url:e.target.value}:v)})}/></label><select aria-label="Tipo de material" value={a.kind} onChange={e=>patch({assets:doc.assets.map((v,j)=>j===i?{...v,kind:e.target.value as typeof a.kind}:v)})}><option value="image">Foto</option><option value="video">Vídeo / reel</option><option value="link">Enlace</option></select>{(['hero','best','main','approved'] as const).map((key,index)=><label className="sk-check" key={key}><input type="checkbox" checked={a[key]} onChange={e=>patch({assets:doc.assets.map((v,j)=>j===i?{...v,[key]:e.target.checked}:v)})}/>{['HERO','BEST PHOTO','MAIN VIDEO','CLIENT APPROVED'][index]}</label>)}<div className="sk-actions"><button onClick={()=>void copy(a.url)}>Copiar enlace</button>{/^https?:/.test(a.url)&&<a href={a.url} download target="_blank" rel="noreferrer">Abrir / descargar original</a>}<button onClick={()=>patch({assets:doc.assets.filter(v=>v.id!==a.id)})}>Quitar</button></div></div>)}</div></>}
 {tab==='warehouse'&&<><p>Define cantidades por personaje. El evento las multiplicará por el número de shows asignados.</p><button onClick={()=>patch({items:[...doc.items,{id:crypto.randomUUID(),name:'',image:'',quantity:1,size:'',location:'',box:'',notes:'',required:true,condition:'',asset_id:'',concept_id:''}]})}>+ Añadir pieza al kit</button>{doc.items.map((item,i)=>{const set=(p:Partial<typeof item>)=>patch({items:doc.items.map((x,j)=>j===i?{...x,...p}:x)});return <article className="sk-kit-item" key={item.id}>{item.image&&<img src={item.image} alt={item.name}/>}<div className="sk-fields"><label>Vincular inventario<select value={item.concept_id} onChange={e=>{const c=data.inventory.find(c=>c.id===e.target.value);set({concept_id:e.target.value,...(c?{name:c.name,image:c.main_image||'',location:c.default_location||''}:{})});}}><option value="">Pieza sin ficha de inventario</option>{data.inventory.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{([['name','Nombre'],['image','Foto URL'],['size','Talla'],['location','Localización'],['box','Caja / estantería / rail'],['notes','Notas'],['condition','Estado'],['asset_id','Nº serie / ID interno']] as const).map(([k,l])=><label key={k}>{l}<input value={item[k]} onChange={e=>set({[k]:e.target.value})}/></label>)}<label>Cantidad por personaje<input type="number" min={1} value={item.quantity} onChange={e=>set({quantity:Number(e.target.value)})}/></label><label><input type="checkbox" checked={item.required} onChange={e=>set({required:e.target.checked})}/> Obligatorio</label></div><button onClick={()=>patch({items:doc.items.filter(v=>v.id!==item.id)})}>Quitar pieza del kit</button></article>;})}</>}
 </fieldset>{['artist','tech','media'].includes(tab)&&<ShowShareLinks key={selected} showId={selected} refresh={shared?.id}/>}</div>}</>}
 </section>;
}
