'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {newTask,taskOverdue,taskPriorities,taskStatuses,workTaskSchema,type WorkTask,type WorkTaskFields} from '@/lib/work-tasks';
import type {WorkspaceReferences} from '@/lib/server/workspace-data';
import {responseJson} from '@/lib/response-json';
import './sales-workspace.css';
type Data={data:WorkTask[];refs:WorkspaceReferences&{proposals:{id:string;title:string}[]};userId:string;canEdit:boolean};
const localDate=(s:string)=>{if(!s)return '';const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function TasksWorkspace({query=''}:{query?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[view,setView]=useState('list'),[owner,setOwner]=useState(''),[filter,setFilter]=useState('open'),[priority,setPriority]=useState(''),[editing,setEditing]=useState<{id:string;version?:number;fields:WorkTaskFields}|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/work-tasks',{cache:'no-store'}),d=await responseJson(r);if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las tareas.');}},[]);
 useEffect(()=>{void load();window.addEventListener('focus',load);return()=>window.removeEventListener('focus',load);},[load]);
 useEffect(()=>{if(editing)dialog.current?.showModal();else dialog.current?.close();},[editing]);
 const open=(t?:WorkTask)=>setEditing({id:t?.id||crypto.randomUUID(),version:t?.version,fields:t?Object.fromEntries(Object.keys(newTask()).map(k=>[k,t[k as keyof WorkTask]??''])) as WorkTaskFields:{...newTask(),owner_id:data?.userId||''}});
 useEffect(()=>{if(!data)return;const url=new URL(window.location.href),id=url.searchParams.get('task');if(id){const t=data.data.find(t=>t.id===id);if(t)open(t);url.searchParams.delete('task');window.history.replaceState(null,'',url);}if(url.searchParams.get('mine')==='1'){setOwner(data.userId);url.searchParams.delete('mine');window.history.replaceState(null,'',url);}const proposal=url.searchParams.get('taskProposal');if(proposal&&data.refs.proposals.some(p=>p.id===proposal)){setEditing({id:crypto.randomUUID(),fields:{...newTask(),title:'Seguimiento de propuesta',proposal_id:proposal,owner_id:data.userId}});url.searchParams.delete('taskProposal');window.history.replaceState(null,'',url);}},[data]);
 async function save(id:string,fields?:WorkTaskFields,version?:number,action='save'){
  if(busy)return false;setBusy(true);setError('');try{const r=await fetch('/api/work-tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,fields,version,action})}),d=await responseJson(r);if(!r.ok)throw Error(d.error);await load();window.dispatchEvent(new Event('plab-inbox-changed'));return true;}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');return false;}finally{setBusy(false);}
 }
 const all=data?.data||[],term=(query+' '+search).toLowerCase().trim();const filtered=all.filter(t=>{
  if(filter==='archive'?!t.deleted_at:!!t.deleted_at)return false;
  if(filter==='open'&&['done','cancelled'].includes(t.status)||filter==='overdue'&&!taskOverdue(t))return false;
  if(filter==='today'&&(!t.deadline||new Date(t.deadline).toLocaleDateString()!==new Date().toLocaleDateString()))return false;
  return (!owner||t.owner_id===owner)&&(!priority||t.priority===priority)&&term.split(/\s+/).every(s=>(t.title+' '+(t.description||'')).toLowerCase().includes(s));
 }).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 const field=(key:keyof WorkTaskFields,value:string)=>setEditing(e=>e?{...e,fields:{...e.fields,[key]:value}}:null);
 const select=(key:keyof WorkTaskFields,label:string,options:{id:string;name:string}[])=><label>{label}<select value={editing?.fields[key]||''} onChange={e=>field(key,e.target.value)}><option value="">Sin asignar</option>{options.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label>;
 const relations=(t:WorkTask)=>[data?.refs.clients.find(x=>x.id===t.client_id)?.company_name,data?.refs.events.find(x=>x.id===t.event_id)?.event_name,data?.refs.proposals.find(x=>x.id===t.proposal_id)?.title,data?.refs.talent.find(x=>x.id===t.talent_id)?.real_name].filter(Boolean).join(' · ');
 const card=(t:WorkTask)=><article className={'sw-task '+(taskOverdue(t)?'sw-overdue':'')} key={t.id}><button className={'sw-check '+(t.status==='done'?'checked':'')} aria-label={`Marcar ${t.title} ${t.status==='done'?'pendiente':'completada'}`} disabled={busy||!data?.canEdit} onClick={()=>void save(t.id,{...t,status:t.status==='done'?'todo':'done'},t.version)}>{t.status==='done'?'✓':''}</button><button className="sw-task-open" onClick={()=>open(t)}><strong>{t.title}</strong><small>{relations(t)||'Sin relación asignada'}</small><small>{data?.refs.members.find(m=>m.id===t.owner_id)?.name||'Sin responsable'} · {t.deadline?new Date(t.deadline).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}):'Sin fecha límite'}</small></button><span className={'sw-pill '+t.priority}>{taskPriorities.find(p=>p[0]===t.priority)?.[1]}</span><select aria-label={`Estado de ${t.title}`} disabled={busy||!data?.canEdit} value={t.status} onChange={e=>void save(t.id,{...t,status:e.target.value as WorkTaskFields['status']},t.version)}>{taskStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button disabled={busy||!data?.canEdit} onClick={()=>void save(t.id,undefined,t.version,t.deleted_at?'restore':'archive')}>{t.deleted_at?'Restaurar':'Archivar'}</button></article>;
 return <section className="sw-workspace"><header className="sw-heading"><div><p className="eyebrow">TRABAJO DEL EQUIPO</p><h1>Tareas</h1><p>Un siguiente paso claro, una persona responsable y todo conectado.</p></div><button className="primary-button" disabled={!data?.canEdit} onClick={()=>open()}>+ Nueva tarea</button></header>
 <div className="sw-stats"><div><span>Pendientes</span><b>{all.filter(t=>!t.deleted_at&&t.status==='todo').length}</b></div><div><span>En curso</span><b>{all.filter(t=>!t.deleted_at&&t.status==='in_progress').length}</b></div><div><span>Vencidas</span><b>{all.filter(t=>!t.deleted_at&&taskOverdue(t)).length}</b></div><div><span>Completadas</span><b>{all.filter(t=>!t.deleted_at&&t.status==='done').length}</b></div></div>
 {error&&!editing&&<p className="sw-error" role="alert">{error} <button onClick={()=>void load()}>Reintentar</button></p>}
 <div className="sw-toolbar"><input aria-label="Buscar tareas" placeholder="Buscar una tarea…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar tareas" value={filter} onChange={e=>setFilter(e.target.value)}>{[['open','Abiertas'],['all','Todas'],['today','Hoy'],['overdue','Vencidas'],['archive','Archivadas']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Responsable" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Todo el equipo</option>{data?.refs.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select aria-label="Prioridad" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas las prioridades</option>{taskPriorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>setOwner(owner?'':data?.userId||'')}>Mis tareas</button><button onClick={()=>setView(view==='list'?'board':'list')}>{view==='list'?'Ver tablero':'Ver lista'}</button><button onClick={()=>void load()}>Actualizar</button></div>
 {!data&&!error?<p>Cargando tareas…</p>:view==='board'?<div className="sw-task-board">{taskStatuses.map(([v,l])=><section key={v}><h2>{l} <small>{filtered.filter(t=>t.status===v).length}</small></h2>{filtered.filter(t=>t.status===v).map(card)}</section>)}</div>:<div>{filtered.map(card)}</div>}{data&&!filtered.length&&<p className="sw-empty">No hay tareas en esta vista. Crea una o cambia los filtros.</p>}
 <dialog className="sw-dialog" ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setEditing(null);}}>{editing&&<><header><div><p className="eyebrow">ORGANIZAR EL SIGUIENTE PASO</p><h2>{editing.version?'Ficha de tarea':'Nueva tarea'}</h2></div><button disabled={busy} onClick={()=>setEditing(null)} aria-label="Cerrar">✕</button></header>{error&&<p className="sw-error" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();const p=workTaskSchema.safeParse(editing.fields);if(!p.success){setError(p.error.issues[0].message);return;}if(await save(editing.id,p.data,editing.version))setEditing(null);}}><fieldset disabled={busy||!data?.canEdit}><label>Título<input required maxLength={200} value={editing.fields.title} onChange={e=>field('title',e.target.value)}/></label><label>Descripción<textarea rows={4} value={editing.fields.description} onChange={e=>field('description',e.target.value)}/></label><div className="sw-form-grid">{select('owner_id','Responsable',data?.refs.members||[])}<label>Fecha y hora límite<input type="datetime-local" value={localDate(editing.fields.deadline)} onChange={e=>field('deadline',e.target.value?new Date(e.target.value).toISOString():'')}/></label><label>Estado<select value={editing.fields.status} onChange={e=>field('status',e.target.value)}>{taskStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Prioridad<select value={editing.fields.priority} onChange={e=>field('priority',e.target.value)}>{taskPriorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><h3>Relacionar con tu trabajo</h3><div className="sw-form-grid">{select('client_id','Cliente',data?.refs.clients.map(c=>({id:c.id,name:c.company_name}))||[])}{select('event_id','Evento',data?.refs.events.map(c=>({id:c.id,name:c.event_name}))||[])}{select('proposal_id','Propuesta',data?.refs.proposals.map(c=>({id:c.id,name:c.title}))||[])}{select('talent_id','Artista / proveedor',data?.refs.talent.map(c=>({id:c.id,name:c.real_name}))||[])}{select('lead_id','Lead',data?.refs.leads.map(c=>({id:c.id,name:c.title}))||[])}{select('opportunity_id','Oportunidad',data?.refs.opportunities.map(c=>({id:c.id,name:c.title}))||[])}</div><footer><button className="primary-button" type="submit">{busy?'Guardando…':'Guardar tarea'}</button></footer></fieldset></form></>}</dialog></section>;
}
