import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireOrganization} from '@/lib/server/auth';
import {invoiceRows} from '@/lib/server/invoices';
import {findSupplierAlias,type Supplier} from '@/lib/bank';
const id=z.string().uuid().nullable();
const schema=z.discriminatedUnion('action',[
 z.object({action:z.literal('allocate'),movement:z.string().uuid(),expense:z.string().uuid(),amount:z.number().int().positive().max(100000000000)}).strict(),
 z.object({action:z.literal('review'),movement:z.string().uuid(),version:z.number().int().positive(),supplier:id,artist:id,event:id,reason:z.enum(['','partial','multiple','retention','commission','refund','error','other']),note:z.string().max(10000)}).strict(),
 z.object({action:z.literal('supplier'),id:z.string().uuid().optional(),name:z.string().trim().min(1).max(500),tax_id:z.string().max(200),iban:z.string().max(100),notes:z.string().max(10000)}).strict()
]);
export async function GET(){const a=await requireOrganization();if('error'in a)return a.error;try{const names=['bank_movements','suppliers','expenses','expense_payments','talent','events','clients','shows','event_shows','payments','expense_artists'];const r=await Promise.all(names.map(n=>invoiceRows(a.supabase,a.membership.organization_id,n)));const legacy=r[2].flatMap(e=>{const p=r[9].find(p=>p.id===e.legacy_payment_id&&p.status==='paid');return p?[{id:p.id,expense_id:e.id,bank_movement_id:null,payment_date:p.paid_on||String(p.created_at).slice(0,10),amount_cents:p.amount_cents,currency:'EUR',method:'',reference:'',note:'Pago histórico registrado en Pagos',created_at:p.created_at}]:[]});return NextResponse.json({movements:r[0],suppliers:r[1].filter(s=>!s.merged_into),expenseArtists:r[10],expenses:r[2],payments:[...r[3],...legacy],talent:r[4],events:r[5].filter(e=>!e.deleted_at&&(e.event_date||e.client_id||e.venue||e.event_name&&e.event_name!=='Evento')),clients:r[6],shows:r[7],eventShows:r[8],canEdit:['admin','producer'].includes(a.membership.role)})}catch{return NextResponse.json({error:'No se pudieron cargar los pagos bancarios.'},{status:500})}}
export async function POST(req:Request){const a=await requireOrganization();if('error'in a)return a.error;if(!['admin','producer'].includes(a.membership.role))return NextResponse.json({error:'No puedes conciliar pagos.'},{status:403});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:p.error.issues[0].message},{status:400});const b=p.data;try{let r;if(b.action==='allocate')r=await a.supabase.rpc('reconcile_bank_payment',{movement:b.movement,expense:b.expense,amount:b.amount});else if(b.action==='review')r=await a.supabase.rpc('review_bank_movement',{movement:b.movement,expected_version:b.version,supplier:b.supplier,artist:b.artist,event:b.event,reason:b.reason,note:b.note});else{const suppliers=await invoiceRows(a.supabase,a.membership.organization_id,'suppliers'),existing=findSupplierAlias(suppliers as unknown as Supplier[],b.name);if(existing&&existing.id!==b.id)return NextResponse.json({error:'Este proveedor ya existe. Abre su ficha para completar los datos.',supplier_id:existing.id},{status:409});const name=existing?.name||b.name;const fields={name,tax_id:b.tax_id,iban:b.iban,notes:b.notes,normalized_name:name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')};r=b.id?await a.supabase.from('suppliers').update(fields).eq('organization_id',a.membership.organization_id).eq('id',b.id):await a.supabase.from('suppliers').insert({...fields,organization_id:a.membership.organization_id});}if(r.error)throw r.error;return NextResponse.json({ok:true})}catch(e){const err=e as {code?:string;message?:string};return NextResponse.json({error:err.code==='P0001'?err.message:err.code==='23505'?'Ya existe este proveedor o la asignación a este gasto.':err.code==='23514'?'Revisa la identidad y los campos del registro.':'No se pudo guardar. Comprueba las relaciones y el saldo disponible.'},{status:400})}}
