import type {Expense,ExpensePayment} from './expenses';
export type Supplier={id:string;name:string;client_id:string|null;talent_id:string|null;aliases:string[];tax_id:string;iban:string;notes:string;deleted_at?:string|null;merged_into?:string|null};
export type BankMovement={id:string;payment_date:string;amount_cents:number;currency:string;original_reference:string;original_concept:string;source_file:string;source_sheet:string;source_row:number;source_data:{artist?:string;concept?:string;supplier?:string;expected?:number;notes?:string};supplier_id:string|null;talent_id:string|null;event_id:string|null;expected_cents:number|null;suggested_event_ids:string[];status:string;issues:string[];resolution_reason:string;resolution_note:string;version:number;created_at:string};
export type BankData={expenseArtists?:{id:string;expense_id:string;event_id:string;talent_id:string;allocated_fee_cents:number|null;source_note:string}[];movements:BankMovement[];suppliers:Supplier[];expenses:(Expense&{supplier_id:string|null;invoice_date:string|null;work_date:string|null})[];payments:(ExpensePayment&{bank_movement_id:string|null})[];talent:{id:string;real_name:string}[];events:{id:string;event_name:string;event_date:string|null;venue:string|null;client_id:string|null}[];clients:{id:string;company_name:string}[];shows:{id:string;name:string}[];eventShows:{event_id:string;show_id:string}[];canEdit:boolean};
export const bankStatuses:Record<string,string>={unmatched:'Sin conciliar',review:'Necesita revisión',reconciled:'Conciliado'};
export function findSupplierAlias(suppliers:(Pick<Supplier,'id'|'name'|'aliases'>&Pick<Supplier,'deleted_at'|'merged_into'>)[],name:string){const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');return suppliers.find(s=>!s.deleted_at&&!s.merged_into&&[s.name,...s.aliases].some(a=>normalize(a)===normalize(name)))}
export const bankIssues:Record<string,string>={duplicate:'Posible pago duplicado',difference:'Diferencia por revisar',artist_missing:'Artista no encontrado',identity_review:'Identidad por confirmar',advance_total_unknown:'Anticipo: total de factura desconocido',multiple_invoices:'Varias facturas en un pago',multiple_events:'Varios eventos: falta repartir el coste',event_review:'Evento por confirmar'};
export const bankReasons:Record<string,string>={partial:'Pago parcial',multiple:'Varias facturas en un pago',retention:'Retención',commission:'Comisión',refund:'Devolución',error:'Error',other:'Otro'};
export function bankAllocated(m:BankMovement,p:BankData['payments']){return p.filter(p=>p.bank_movement_id===m.id).reduce((s,p)=>s+p.amount_cents,0)}
export function bankTotals(m:BankMovement[],p:BankData['payments']){return m.reduce((s,m)=>{s.total+=m.amount_cents;s.allocated+=bankAllocated(m,p);if(m.status!=='reconciled')s.review+=m.amount_cents;if(m.issues.includes('duplicate')&&!m.resolution_note)s.alerts++;return s},{total:0,allocated:0,review:0,alerts:0})}
