var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/event-board/route.js")
R.c("server/chunks/node_modules_next_108t5mi._.js")
R.c("server/chunks/node_modules_zod_v4_classic_1puff4q._.js")
R.c("server/chunks/node_modules_zod_v4_core_03961oy._.js")
R.c("server/chunks/node_modules_zod_v4_locales_11ffzkd._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00x2u05._.js")
R.c("server/chunks/node_modules_0lqrqw-._.js")
R.c("server/chunks/[root-of-the-server]__10e3ubo._.js")
R.c("server/chunks/_next-internal_server_app_api_event-board_route_actions_0f41s6j.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/event-board/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/event-board/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
