import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireOrganization} from '@/lib/server/auth';
import {invoiceRows} from '@/lib/server/invoices';
import {dataReview} from '@/lib/data-review';
// event_talent has a composite key, so it must not use invoiceRows' id ordering.
async function load(db:Parameters<typeof invoiceRows>[0],org:string){const names=['talent','suppliers','events','expenses','expense_payments','bank_movements','expense_artists','invoices'];const data=Object.fromEntries(await Promise.all(names.map(async name=>[name,await invoiceRows(db,org,name)])));const assignments=await db.from('event_talent').select('*').eq('organization_id',org).range(0,9999);if(assignments.error)throw assignments.error;return {...data,event_talent:assignments.data};}
export async function GET(){const a=await requireOrganization();if('error'in a)return a.error;try{const d=await load(a.supabase,a.membership.organization_id);return NextResponse.json({rows:dataReview(d),artists:d.talent,suppliers:d.suppliers,assignments:d.event_talent,expenses:d.expenses,canEdit:['admin','producer'].includes(a.membership.role)});}catch{return NextResponse.json({error:'No se pudo cargar la revisión de datos.'},{status:500});}}
export async function POST(req:Request){const a=await requireOrganization();if('error'in a)return a.error;if(!['admin','producer'].includes(a.membership.role))return NextResponse.json({error:'Tu perfil no permite fusionar fichas.'},{status:403});const p=z.object({entity:z.enum(['talent','suppliers']),primary:z.uuid(),duplicate:z.uuid(),note:z.string().trim().min(10).max(2000)}).strict().safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:'Selecciona las fichas e indica la confirmación de identidad.'},{status:400});const r=await a.supabase.rpc('merge_identity',{main_id:p.data.primary,duplicate_id:p.data.duplicate,entity:p.data.entity,review_note:p.data.note});return r.error?NextResponse.json({error:r.error.code==='P0001'?r.error.message:'No se pudo fusionar; los datos anteriores se conservan.'},{status:409}):NextResponse.json(r.data);}
