-- Restrict the initial schema before it is used with business data.
create or replace function public.has_org_role(target_org uuid, permitted text[]) returns boolean
language sql stable security definer set search_path = public, pg_temp as $$
  select exists(select 1 from public.organization_members
    where organization_id=target_org and user_id=auth.uid() and role::text=any(permitted));
$$;
revoke all on function public.has_org_role(uuid,text[]) from public;
grant execute on function public.has_org_role(uuid,text[]) to authenticated;

do $$ declare p record; t text; roles text[]; begin
  for p in select tablename,policyname from pg_policies where schemaname='public' and tablename not in ('organizations','users','organization_members') loop
    execute format('drop policy %I on public.%I',p.policyname,p.tablename);
  end loop;
  foreach t in array array['clients','client_contacts','leads','events','event_requirements','event_financials','talent','talent_disciplines','talent_rates','talent_media','event_talent','suppliers','concepts','storage_locations','assets','asset_movements','proposals','proposal_options','proposal_items','tasks','payments','communications','notes','files','pricing_rules','activity_log','ai_activity'] loop
    roles := case
      when t in ('activity_log','ai_activity','payments') then array['admin']
      when t in ('event_financials','talent','talent_disciplines','talent_rates','talent_media','suppliers','event_talent') then array['admin','producer']
      when t in ('assets','asset_movements','storage_locations','event_requirements','events') then array['admin','producer','wardrobe']
      else array['admin','producer','sales'] end;
    execute format('create policy role_read on public.%I for select to authenticated using (public.has_org_role(organization_id,%L::text[]))',t,roles);
    if t in ('activity_log','ai_activity') then continue; end if;
    if t='pricing_rules' then roles:=array['admin']; end if;
    if t='events' then roles:=array['admin','producer']; end if;
    execute format('create policy role_insert on public.%I for insert to authenticated with check (public.has_org_role(organization_id,%L::text[]))',t,roles);
    execute format('create policy role_update on public.%I for update to authenticated using (public.has_org_role(organization_id,%L::text[])) with check (public.has_org_role(organization_id,%L::text[]))',t,roles,roles);
    -- No hard deletion of business rows from application sessions.
  end loop;
end $$;

create policy wardrobe_own_tasks_read on public.tasks for select to authenticated using
  (public.has_org_role(organization_id,array['wardrobe']) and owner_id=auth.uid());
-- Tasks assigned to wardrobe are read-only until the scoped completion flow is implemented.

-- All references are checked against the row's organisation, including owners.
create or replace function public.enforce_tenant_references() returns trigger language plpgsql
security definer set search_path=public,pg_temp as $$
declare fk record; target uuid; row_org uuid; target_org uuid; begin
  row_org := (to_jsonb(new)->>'organization_id')::uuid;
  if tg_op='UPDATE' and row_org <> (to_jsonb(old)->>'organization_id')::uuid then
    raise exception 'No se puede cambiar la organización de un registro.';
  end if;
  for fk in
    select a.attname as col, c.confrelid::regclass as target_table, c.confrelid as target_oid
    from pg_constraint c join pg_attribute a on a.attrelid=c.conrelid and a.attnum=c.conkey[1]
    where c.contype='f' and c.conrelid=tg_relid and array_length(c.conkey,1)=1
  loop
    target := (to_jsonb(new)->>fk.col)::uuid;
    if target is null or fk.target_table='public.organizations'::regclass then continue; end if;
    if fk.target_table='public.users'::regclass then
      if not exists(select 1 from public.organization_members where organization_id=row_org and user_id=target) then
        raise exception 'La persona responsable no pertenece al equipo.';
      end if;
    elsif exists(select 1 from pg_attribute where attrelid=fk.target_oid and attname='organization_id' and not attisdropped) then
      execute format('select organization_id from %s where id=$1',fk.target_table) into target_org using target;
      if target_org is distinct from row_org then raise exception 'La relación no pertenece a esta organización.'; end if;
    end if;
  end loop;
  return new;
end; $$;

-- Audit is generated by the database, never by trusting a caller-supplied actor.
create or replace function public.audit_business_change() returns trigger language plpgsql
security definer set search_path=public,pg_temp as $$
begin
  insert into public.activity_log(organization_id,actor_id,entity_type,entity_id,action,before_data,after_data)
    values(new.organization_id,auth.uid(),tg_table_name,new.id,tg_op,
      case when tg_op='UPDATE' then to_jsonb(old) else null end,to_jsonb(new));
  return new;
end; $$;

do $$ declare t text; begin
  foreach t in array array['clients','client_contacts','leads','events','event_requirements','event_financials','talent','talent_disciplines','talent_rates','talent_media','event_talent','suppliers','concepts','storage_locations','assets','asset_movements','proposals','proposal_options','proposal_items','tasks','payments','communications','notes','files','pricing_rules'] loop
    execute format('create trigger enforce_tenant before insert or update on public.%I for each row execute function public.enforce_tenant_references()',t);
  end loop;
  foreach t in array array['clients','client_contacts','events','event_requirements','tasks','talent','leads','proposals','proposal_options','proposal_items','assets','pricing_rules'] loop
    execute format('create trigger audit_change after insert or update on public.%I for each row execute function public.audit_business_change()',t);
  end loop;
end $$;

alter table public.clients add constraint client_name_valid check(length(trim(company_name)) between 1 and 200);
alter table public.clients add constraint client_notes_limit check(notes is null or length(notes)<=10000);
alter table public.events add constraint event_name_valid check(length(trim(event_name)) between 1 and 200);
alter table public.events add constraint event_guests_limit check(guest_count is null or guest_count between 0 and 1000000);
alter table public.events add constraint event_brief_limit check(brief is null or length(brief)<=10000);
alter table public.tasks add constraint task_title_valid check(length(trim(title)) between 1 and 200);
alter table public.tasks add constraint task_notes_limit check(description is null or length(description)<=10000);
alter table public.event_requirements add constraint requirement_label_valid check(length(trim(label)) between 1 and 200);
alter table public.client_contacts add constraint contact_name_valid check(length(trim(full_name)) between 1 and 200);
alter table public.tasks add column automation_key text;
create unique index tasks_event_automation_key on public.tasks(event_id,automation_key) where automation_key is not null;

create or replace function public.prepare_confirmed_event() returns trigger language plpgsql
security definer set search_path=public,pg_temp as $$
declare item text; begin
  if new.status not in ('confirmed','production') or new.deleted_at is not null then return new; end if;
  foreach item in array array['Confirmar artistas','Preparar vestuario','Confirmar horarios con el cliente'] loop
    insert into public.tasks(organization_id,title,event_id,owner_id,priority,automation_key)
    values(new.organization_id,item,new.id,new.owner_id,'high',item)
    on conflict(event_id,automation_key) where automation_key is not null do nothing;
  end loop;
  return new;
end; $$;
create trigger event_production_tasks after insert or update of status on public.events
for each row execute function public.prepare_confirmed_event();

create or replace function public.bootstrap_performance_lab() returns uuid language plpgsql
security definer set search_path=public,pg_temp as $$
declare result uuid; begin
  if auth.uid() is null then raise exception 'Inicia sesión.'; end if;
  if not exists(select 1 from auth.users where id=auth.uid() and lower(email)='plabcreativesos@gmail.com' and email_confirmed_at is not null) then
    raise exception 'El administrador fundador debe usar el correo verificado plabcreativesos@gmail.com.';
  end if;
  perform pg_advisory_xact_lock(20260911);
  select organization_id into result from public.organization_members where user_id=auth.uid() limit 1;
  if result is not null then return result; end if;
  if exists(select 1 from public.organizations where slug='performance-lab') then raise exception 'La organización ya existe. Solicita acceso al administrador.'; end if;
  insert into public.users(id,full_name) values(auth.uid(),'Manuel') on conflict(id) do nothing;
  insert into public.organizations(name,slug) values('Performance Lab','performance-lab') returning id into result;
  insert into public.organization_members(organization_id,user_id,role) values(result,auth.uid(),'admin');
  return result;
end; $$;
revoke all on function public.bootstrap_performance_lab() from public;
grant execute on function public.bootstrap_performance_lab() to authenticated;

-- Protect the last administrator and organisation membership from reassignment.
create or replace function public.protect_membership() returns trigger language plpgsql
security definer set search_path=public,pg_temp as $$
begin
  perform 1 from public.organizations where id=old.organization_id for update;
  if tg_op='UPDATE' and (new.organization_id<>old.organization_id or new.user_id<>old.user_id) then raise exception 'La identidad de un miembro no se puede cambiar.'; end if;
  if old.role='admin' and (tg_op='DELETE' or new.role<>'admin') and
    (select count(*) from public.organization_members where organization_id=old.organization_id and role='admin')<=1
    then raise exception 'El equipo necesita al menos un administrador.'; end if;
  if tg_op='DELETE' then return old; end if; return new;
end; $$;
create trigger protect_member before update or delete on public.organization_members for each row execute function public.protect_membership();

revoke all on function public.enforce_tenant_references() from public;
revoke all on function public.audit_business_change() from public;
revoke all on function public.prepare_confirmed_event() from public;
revoke all on function public.protect_membership() from public;
revoke all on function public.handle_new_user() from public;
revoke all on function public.is_org_member(uuid) from public;
revoke all on function public.is_org_admin(uuid) from public;
grant execute on function public.is_org_member(uuid),public.is_org_admin(uuid) to authenticated;
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
